### ISSUE TITLE
wallpaper on phone

### ISSUE THREAD

**Issue by Vladislavik** [theothernt/AerialViews#100]
Please allow to use it as wallpaper app, I want to use it on android phone as wallpaper

**Comment by theothernt** [comment]
Do you already use Aerial Views as a screensaver on your phone?

**Comment by Vladislavik** [comment]
Yes it work fine on Galaxy s23

**Comment by theothernt** [comment]
I did some research on wallpaper functionality but it's quite different from how a screensaver works - at least on Android - so I don't think it's suitable for the app.

If you were to download the videos, is there another wallpaper app available on Android that could use them?

**Comment by Vladislavik** [comment]
It is hard to find this app, that allow add own videos, download all videos and add it to this app :)
