### ISSUE TITLE
Best authentication method for SMB server with Active Directory Authentication?

### ISSUE THREAD

**Issue by JustMatthewDEV** [theothernt/AerialViews#103]
I was trying to connect my Samba Server, where I host all the videos of a car store (basically, I want to put a screensaver with my videos when nobody is streaming to it). 
The server authenticates via Active Directory (Kerberos) user and password. 
But it says Can't connect to Server Authentication Failed. 

Maybe I need to put my domain name like example\user or user@example.local? Everything is ok with the user, I can authenticate without any problem in another file app on my Chromecast, but I can't do it on Aerial. 

I have a Chromecast 4K with Google TV , Android 13 and Aerial Views downloaded via Google Play (lastest version)

**Comment by theothernt** [comment]
The option to specify a domain or workgroup is in the code, there's no UI option for it, it defaults to WORKGROUP - that's something I can fix in the next release, but it won't be due for a couple of weeks?

In the meantime, you can try putting `domain\username` as the username, although I can't test that myself as I don't have a domain setup at home.

**Comment by theothernt** [comment]
v1.5 has just been released on GitHub with this fix. It should be released on the Play Store, etc in the next couple of weeks.
