### ISSUE TITLE
Script Collection (Bulk Download Videos, etc.)

### ISSUE THREAD

**Issue by ArmoredCavalry** [theothernt/AerialViews#106]
Started a discussion regarding this over on this [PR](https://github.com/theothernt/AerialViews/pull/105). Would be nice to have a collection of scripts for various actions, first being to bulk-download the aerial videos for local playback. Here is an initial example, written in Python - 

https://gist.github.com/ArmoredCavalry/a902df9b44d34963e1890a4038773b63

Can use this issue for discussion of what parameters / options would be good to have, etc.?

**Comment by theothernt** [comment]
Ok, sounds good. For the download script, just a few changes from your initial version...

1. The ability to specify all or just some of the videos
2. The quality - SDR, HDR etc

**Comment by theothernt** [comment]
Adding @peat80 to the conversion.

Would it be possible get the script you used to pull down POI json files for the Apple videos?

What I'd like to do in future is create a /Scripts folder and put them all there.
