### ISSUE TITLE
Option to not add spaces before and after dashes?

### ISSUE THREAD

**Issue by wrybread** [theothernt/AerialViews#107]
I use Aerial Views to display my drone footage, and the files have names like "2023-05-17-0931 - Up in the Clouds.MP4". When playing in Aerial Views the spaces make the date in the title confusing to read, like "2023 - 05 - 17 - 0931 - Up in the Clouds". Would it be possible to add an option to not modify the filenames? Or maybe the ability already exists and I haven't found it?

And thanks again for the great work.

**Comment by theothernt** [comment]
Try disabling the _Settings > Appearance > Use filename as location_ ?

**Comment by wrybread** [comment]
The problem is then the filename isn't displayed. I like having the filename displayed since it tells the date of the flight and where the flight happened. In other words I do want the location, I just don't want it to change the format of it.

**Comment by theothernt** [comment]
Oh ok, understood. Let me have a think about how I can change the options menu...

1. Disabled (don't show location based on filename)
2. Use formatting (country-some.place.mp4)
3. Show filename as-is.

**Comment by wrybread** [comment]
> 3. Show filename as-is.

That would be great. Ideally it would omit the file extension.

**Comment by theothernt** [comment]
v1.5 has just been released but it's likely the improvement mentioned above will be in the next release, assuming no major issues!

**Comment by theothernt** [comment]
This update is now live in the Play Store and Amazon Appstore.
