### ISSUE TITLE
How to set up a server??

### ISSUE THREAD

**Issue by MarshMeadow** [theothernt/AerialViews#113]
What is the best way to set up a server??

**Comment by theothernt** [comment]
What kind of server, and what would you like to do with it?

Also, do you have an existing PC or Mac, or did you want a new device to act as the server?

**Comment by theothernt** [comment]
If you're building a PC and running Windows, then all you need to do is...

1. Create a folder, place all the videos in that folder
2. Share the folder - allowing access to that folder over the network
3. Enter those details into Aerial Views and it should be able to show those videos

For setting up file sharing on Windows, please [refer to this support document from Microsoft](https://support.microsoft.com/en-us/windows/file-sharing-over-a-network-in-windows-b58704b2-f53a-4b82-7bc1-80f9994725bf).

**Comment by theothernt** [comment]
> sounds good, i will check it out later, thanks!

Best of luck, and if you run into any problems with Aerial Views, please feel free to open another issue or comment here.
