### ISSUE TITLE
Recursive support for Samba/SMB (subfolders)

### ISSUE THREAD

**Issue by briantho** [theothernt/AerialViews#114]
I just tried this app on my chromecast google tv edition. I sucessfully enabled smb and got it working for videos in a single directory. However this app does not seem to do recursive scanning, so subfolders with videos aren't playable. Any way this could be implemented??? I eagerly await this, as well as [photo support](https://github.com/theothernt/AerialViews/issues/95). Thanks.

**Comment by theothernt** [comment]
I can add this feature to a future release, it was left out mainly because there could be performance issues if there are lots of folders + files on the SMB share.

**Comment by briantho** [comment]
Got it. Would probably be worth doing a toggle setting to disable or enable subfolder support. I have a drive mapped that has about 400gb of home movies in subfolders by year that i would love to have as a background screensaver on my android tv. same goes for my pictures. they are roughly organized by year and location with a subfolder for each yeah and location. I'd love to start displaying both photos and videos as a screensaver for android tv. 

regarding performance, what do you mean? cpu usage on the chromecast? or something else?

**Comment by theothernt** [comment]
Agreed, I'll add it as an optional setting, disabled by default.

Although the Chromecast with Google TV is a low power device, my app isn't too demanding - the main issue is that SMB/Samba can be slow when traversing lots of folders and files. You'll have to let me know what the performance is like on your system!

**Comment by theothernt** [comment]
@briantho would you be willing to test the feature in a beta version of the app?

**Comment by briantho** [comment]
Sure, I'd be happy to test. Do you have photos working, or just videos only (for now). Either way, i can try it out.

**Comment by theothernt** [comment]
Thanks, here is [Aerial Views v.1.5.1 beta1](https://www.dropbox.com/scl/fi/pzrkdst43gk0kpftdvd9q/aerial-views-1.5.1-beta1.apk?rlkey=og283504qqt3g40bvutbj3weu&dl=0) with SMB subfolder support.

Let me know how it performs, especially when you see "Loading..." - that should only appear for a second or two! An ethernet connection should help a bit!

As for image support, that is on the list but I have a few other features to add first. Adding image support does require a lot of the app to be rewritten or re-organised.

**Comment by briantho** [comment]
Working just fine. I just went from having 0 videos previously, to 103902 videos. Granted there are a total of 206809, but not all it says are playable. Loading takes about 20 seconds which is fine for me. I don't mind at all if it takes that long. Perfectly fine for a screensaver, and it doesn't buffer or anything during playback. 

I also wanted to ask if there is a way to add a second smb share? Is there? If not could you add this feature?

Thanks again for this great app.

**Comment by theothernt** [comment]
Glad to hear it's working!

Regarding the files that are not playable, do you think they are less common video formats or could they be images?

And currently only 1 SMB share is supported. It is possible to add support for a 2nd share/folder but I'm not sure when that will appear.

**Comment by briantho** [comment]
> Glad to hear it's working!
> 
> Regarding the files that are not playable, do you think they are less common video formats or could they be images?
> 
> And currently only 1 SMB share is supported. It is possible to add support for a 2nd share/folder but I'm not sure when that will appear.

Is there any way to determine what was not playable, via logs or something? I pointed it to a directory with both pictures and home movies. Prehaps the unplayable files were pictures? i'm not sure. Let me know if there is some way to determine what the problem files are.

**Comment by theothernt** [comment]
> Is there any way to determine what was not playable, via logs or something? I pointed it to a directory with both pictures and home movies. Prehaps the unplayable files were pictures? i'm not sure. Let me know if there is some way to determine what the problem files are.

There is no specific logging showing which files are skipped, etc but it's probably images. I hope to improve to logging for all that in a future version.

**Comment by briantho** [comment]
Ah ok. I'm going to go ahead and close this now, as it does work. Please let me know when this does get merged into the latest release version, so i can keep the app up to date via the play store. Thanks again

**Comment by theothernt** [comment]
> Ah ok. I'm going to go ahead and close this now, as it does work. Please let me know when this does get merged into the latest release version, so i can keep the app up to date via the play store. Thanks again

Will do, I expect to release it in the next week (or two at most!)

**Comment by theothernt** [comment]
This update is now live on the Play Store and Amazon Appstore.
