### ISSUE TITLE
Suggestion : custom font and clock and location position

### ISSUE THREAD

**Issue by SeanDylan** [theothernt/AerialViews#115]
**Describe the solution you'd like...**

This type of customization can give you your own style and font

**Comment by theothernt** [comment]
I'm actually working on that currently, partly because there are going to be more overlays added, so people will have to decide which ones they want to show and where.

The plan at the moment is for the next version of the app (1.5.1) to have 4 slots with more added later...

* bottom left x 2
* bottom right x 2

As for fonts, I'll be making Open Sans the new default but you can change it to other styles of Roboto and a couple of other fonts built-into Android TV.

**Comment by jhoblitt** [comment]
I discovered this app earlier today and quickly turned up the font size because it was a bit difficult to read the default against some of the videos. However, what I would actually prefer is the ability to increase the font weight / bold rather than having the location string spanning most of the screen.  I was looking for an app to display a gallery from a local Linux box and ended up being mesmerized by some of the videos.  Thank you for all the hard work it's clearly taken to make this a polished experience.

**Comment by theothernt** [comment]
> I discovered this app earlier today and quickly turned up the font size because it was a bit difficult to read the default against some of the videos. However, what I would actually prefer is the ability to increase the font weight / bold rather than having the location string spanning most of the screen. I was looking for an app to display a gallery from a local Linux box and ended up being mesmerized by some of the videos. Thank you for all the hard work it's clearly taken to make this a polished experience.

Thanks for the nice comments!

I agree about the text options and that should improve a lot over the next couple of updates ie. a new default font (Open Sans), font weight/style options, etc

**Comment by SeanDylan** [comment]
> I'm actually working on that currently, partly because there are going to be more overlays added, so people will have to decide which ones they want to show and where.
> 
> The plan at the moment is for the next version of the app (1.5.1) to have 4 slots with more added later...
> 
> * bottom left x 2
> * bottom right x 2
> 
> As for fonts, I'll be making Open Sans the new default but you can change it to other styles of Roboto and a couple of other fonts built-into Android TV.

What about fonts that you can choose from your device storage? I actually want to use google sans instead of any other font

**Comment by theothernt** [comment]
@SeanDylan @jhoblitt  I have an example to run by you both...

The ability to move around overlays (clock, location, etc) will mean adding new menu options. There will be 'slots' in each corner of the screen where you can assign/pick overlays. This will be in the form of drop down menus, one for each slot.

1. You have two slots, left and right (keeping things simple here!)
2. In each slot, you can pick 1 item such as location, clock, etc
3. Lets say you have the **clock** assigned to the **right slot** and want to change it to the **left**
4. In the drop down menu for the left slot, I see "Clock (right slot)" and select it
5. The right slot now shows "Clock", the left slot is now set to "Empty" and a short notification is displayed saying "Clock removed from right slot"

Does all of that make sense? ...I'm tying to keep things simple and not present lots of yes/no dialogue boxes.

**Comment by jhoblitt** [comment]
@theothernt Fixed positions sound reasonable to me.  Going back to my reference to magicmirror, MM supports a number of fixed locations: https://docs.magicmirror.builders/modules/configuration.html#position

**Comment by theothernt** [comment]
> @theothernt Fixed positions sound reasonable to me. Going back to my reference to magicmirror, MM supports a number of fixed locations: https://docs.magicmirror.builders/modules/configuration.html#position

Thanks - and does the explanation of how to change overlays make sense? ie. if you want to move an overlay to a different slot, you don't have to remove it first - you just pick the overlay in the new slot and it's removed from the old slot (with a small notification)

**Comment by theothernt** [comment]
Ok, this feature (overlays/widgets) is nearly finished... is anyone able to test a beta version?

**Comment by SeanDylan** [comment]
> Ok, this feature (overlays/widgets) is nearly finished... is anyone able to test a beta version?

I can. For me it's friday today so i have the time

**Comment by SeanDylan** [comment]
Btw sorry for the late reply i have some things to do during that

**Comment by theothernt** [comment]
> Btw sorry for the late reply i have some things to do during that

No problem at all. I've been running this build for a few weeks now so I think it's ready. I'll release it today 😅

**Comment by theothernt** [comment]
Aerial Views 1.6 has been released with the new slot/overlays system, let me know what you think...

https://github.com/theothernt/AerialViews/releases/tag/1.6.0
