### ISSUE TITLE
Weather 3d background at screensaver real time

### ISSUE THREAD

**Issue by SeanDylan** [theothernt/AerialViews#119]
Just like google pixel tablet i would rather have a 3d screensaver of weather at real time up in the clouds (of course with real-time weather conditions) and also have a option for weather conditions in aerial videos if possible

**Comment by theothernt** [comment]
There is already [a request for a weather feature](https://github.com/theothernt/AerialViews/issues/36). I'll be posting updates there.

The feature itself will not feature 3D, etc - whole a video plays, 2D icons will be displayed showing the current weather and temperature.
