### ISSUE TITLE
Apple videos not downloading

### ISSUE THREAD

**Issue by Shawn9347** [theothernt/AerialViews#121]
Hi, 
I was trying to download Apple videos from the links in the README. 

What happened was that the downloads don't start when choosing one of the qualities. The videos from other creators do download however. 

Anyone else have this issue? Please let me know.

**Comment by theothernt** [comment]
It looks like Chrome (and maybe other browsers) block 'insecure' downloads so you either have to right-click on the link or change a security settings for a few minutes.

I'll look into a fix in the meantime and report back.

**Comment by theothernt** [comment]
Ok, I've changed the links back to HTTPS which removes the 'insecure' error but causes another as Apple's SSL cert isn't valid (never was, they're not going to fix it).

Even though you get an error, if you accept it once, you can then go back and download all of the other videos with 1 click and no further errors.

Let me know how you get on!

**Comment by Shawn9347** [comment]
Oh, sorry for not responding. I worked tho. Bit late xD.

**Comment by theothernt** [comment]
> Oh, sorry for not responding. It worked tho. Bit late xD.

No problem at all, glad you got it working - enjoy the videos 😀
