### ISSUE TITLE
URI to launch application?

### ISSUE THREAD

**Issue by bolt-snap-bolt** [theothernt/AerialViews#122]
Hi,

Wondering if AerialViews currently provides a deep link URI to allow programmatic launching of the application?

My use case is automation via Home Assistant's native Android TV integration. I'd like to be able to launch AerialViews (or trigger the Android device to start the configured screensaver) similar to the way I am able to launch Plex via a "plex://" URI.

I had a look through the AndroidManifest.xml file for the pattern I was expecting but didn't see a <data android:scheme="xyz"/> section.

See https://community.home-assistant.io/t/android-tv-remote-app-links-deep-linking-guide/567921 more background information.

**Comment by theothernt** [comment]
Aerial Views doesn't have a deep link URI but I can add one - that shouldn't be a problem.

I'll probably go with aerialviews://

**Comment by theothernt** [comment]
Also, just read that Home Assistant has an ADB add-in that can call Android Intents - which should give you the same result.

**Comment by bolt-snap-bolt** [comment]
Can you provide more details on what command I need to send via ADB to launch Aerial Views?

The integration provides a way to launch apps from a list but it opens to the text menu, not the actual screen saver content.
I've tried various manual commands based on the info I found [here](https://gist.github.com/mcfrojd/9e6875e1db5c089b1e3ddeb7dba0f304) but without success.

**Comment by theothernt** [comment]
Glad you got it working!

I'll keep this issue open until I have an update with the new URI support.

**Comment by bolt-snap-bolt** [comment]
I appreciate the prompt responses & support. The app is awesome by the way, thanks very much!

**Comment by mrkhachaturov** [comment]
![image](https://github.com/theothernt/AerialViews/assets/105451445/6ae43015-e0ed-4a17-9b41-8900a9934b8f)

If will awesome if you make an option to use web url instead of video for screensaver.
Screenshot is from magic mirror project, usually it is used to display information on mirrors. But you can simply access it by url.

It allows you to integrate your calendar with events, weather, news feed and so on.

So imagine when tv goes to screen saver mode you can see all that information. 

I am already looking for an option, to change background in magic mirror to video. Maybe it will be possible to show all that information in front of video 🤪!

Great job, like your application very much 🚀

**Comment by theothernt** [comment]
> If will be awesome if you can make an option to use web url instead of video for screensaver. Screenshot is from magic mirror project, usually it is used to display information on mirrors. But you can simply access it by url.

Sorry to disappoint you but this issue relates to a URI (different to a URL) which can be called by an automation (Home Assistant, in this case) to start the app only. It does not supply content or change anything about the app, only start it.

Also, Aerial Views is designed to play video - it's basically a video player with some text boxes. It cannot show web content and there are no plans to add such a feature.

**Comment by mrkhachaturov** [comment]
> > If will be awesome if you can make an option to use web url instead of video for screensaver. Screenshot is from magic mirror project, usually it is used to display information on mirrors. But you can simply access it by url.
> 
> Sorry to disappoint you but this issue relates to a URI (different to a URL) which can be called by an automation (Home Assistant, in this case) to start the app only. It does not supply content or change anything about the app, only start it.
> 
> Also, Aerial Views is designed to play video - it's basically a video player with some text boxes. It cannot show web content and there are no plans to add such a feature.

Thank you anyway
