### ISSUE TITLE
Broken link on download page

### ISSUE THREAD

**Issue by alonezw** [theothernt/AerialViews#124]
On page: https://aerial-videos.netlify.app/#robin-fourcade i found broken link on video # 2 , 1080p SDR.

incorrect link:
https://github.com/RobinFrcd/AerialShots/releases/download/reunion-2022/robinfrcd_reunion_CapMechan2_1080p_hevc.m4v
correct link:
https://github.com/RobinFrcd/AerialShots/releases/download/reunion-2022/robinfrcd_reunion_CapMechant2_1080p_hevc.m4v

**Comment by theothernt** [comment]
Thanks for reporting the mistake!

I've fixed the issue on the Aerial Views website, which is live and, and in Aerial Views which will be in the next update 🥳
