### ISSUE TITLE
Add option to disable media control button pass-through

### ISSUE THREAD

**Issue by MarcelBochtler** [theothernt/AerialViews#126]
Hi,

while I like the idea that media buttons, like resume, can be passed to the running application, if it doesn't work reliably this is bad UX as buttons behave differently depending on the application currently running.
Even worse, some applications don't react to the resume button at all.

For me this happens while using [Just Player](https://github.com/moneytoo/Player) as an external player for [Jellyfin](https://github.com/jellyfin/jellyfin-androidtv). Pausing Just Player, waiting for AerialViews to start, and pressing the resume button on my Shield TV Remote doesn't do anything.
Issue #30 reports something similar.

I think it is worth to consider adding an option to disable the pass-through of any buttons to other apps than AerialViews.
With this option users could configure AerialViews to always behave the same, no matter what media player is currently running.

**Comment by theothernt** [comment]
Sounds like a good idea, I'll add it in the next update.

The default will probably be to allow the pass through of the media buttons - I just have to figure out how to phrase it.

**Comment by theothernt** [comment]
v1.6.3 is now live on GitHub, it contains an option to disable the media button passthrough. I should be available on the Play Store, etc in the next 5 days or so.
