### ISSUE TITLE
Play Store Release

### ISSUE THREAD

**Issue by JeremyKennedy** [theothernt/AerialViews#13]
Hey, I see you are planning a Play Store release in #11. This is great! I just wanted to open this issue to track that task, and whoever wants to be notified when it's ready can subscribe to this issue.

Thanks!

**Comment by theothernt** [comment]
That's a great idea! My current plan is...

1. Rename the app and repo
2. Create a new icon + Play Store assets
3. Simplify menu options to 2) Apple videos (remote, local, network) and b) Any videos (remote, local, network)

This should be v0.99. If there are issues and fixes, there'll be a v0.99.1 etc. 

If all is well, then it'll move to the Play Store as v1.0

**Comment by jacklongford** [comment]
> That's a great idea! My current plan is...
> 
> * [ ]   Rename the app and repo
> * [ ]   Create a new icon + Play Store assets
> * [ ]   Simplify menu options to 2) Apple videos (remote, local, network) and b) Any videos (remote, local, network)
> 
> This should be v0.99. If there are issues and fixes, there'll be a v0.99.1 etc.
> 
> If all is well, then it'll move to the Play Store as v1.0

Hello, I was just wondering if there is a current ETA for when the app will be put on the Play Store. Thanks

**Comment by theothernt** [comment]
> Hello, I was just wondering if there is a current ETA for when the app will be put on the Play Store. Thanks

I think the current ETA is mid-October. I expected development + icons to be done in 2 weeks, then I'd like to have that version tested by the community to make sure there are no critical issues, then submit to the Play Store.

**Comment by theothernt** [comment]
Might be a couple more weeks. There are a couple of crashes I'm trying to track down (very rare I think!) and progress on the icon is slow due to lack of spare time.

I know some people are waiting on the Play Store release so thanks for being so patient!

**Comment by Shawzborne** [comment]
> Might be a couple more weeks. There are a couple of crashes I'm trying to track down (very rare I think!) and progress on the icon is slow due to lack of spare time.
> 
> 
> 
> I know some people are waiting on the Play Store release so thanks for being so patient! 

Looking forward to it

**Comment by theothernt** [comment]
Ok, I think everything is now ready to submit!

I just have to tweak the build process a bit so it outputs different builds for Google Play Store and GitHub - both with slightly different icons.

... so it should be a matter of days before it appears in the store 🥳

**Comment by theothernt** [comment]
27th Dec 2021 - Waiting on review by Google Play Store. Can take between a day and a week, or so I've read 🤞

**Comment by prabjots07** [comment]
Thank you for keeping us updated. Can you please update apk under releases too? Thank you 😊

**Comment by theothernt** [comment]
> Thank you for keeping us updated. Can you please update apk under releases too? Thank you 😊

Yeah, that's the plan. Once the Google Play Store release is approved, the docs + releases will be updated on here.

Going forward, beta + stable releases will be on GitHub, but only stable releases will be on the Play Store.

**Comment by theothernt** [comment]
At long last I can now say - Aerial Views has been approved in the Google Play Store! 🥳🥂

I've only just pressed the 'publish' button so it may take a while to appear.

Also, please note that both versions of the app (GitHub and Play Store) cannot be installed at the same time, you have to pick one or the other.
