### ISSUE TITLE
Hope the app supports Chinese

### ISSUE THREAD

**Issue by juneix** [theothernt/AerialViews#130]
Hello, I come from China and I really like the software you developed. It performs perfectly on my TV and projector. I would like to recommend it to my friends, but the English settings interface has a certain threshold for some Chinese users. Is there any way to participate in Chinese localization work? For example, third-party platforms like Transifex？

**Comment by theothernt** [comment]
Thank you for the offer, it would be great if you could help translate the app into Chinese.

Which dialect of Chinese would you like to translate into?

We can use a site called [Lokalise](https://lokalise.com/). I can send an invite to join the Aerial Views team, I just need an email address - which you can send privately if you like?

**Comment by juneix** [comment]
> Thank you for the offer, it would be great if you could help translate the app into Chinese.
> 
> Which dialect of Chinese would you like to translate into?
> 
> We can use a site called [Lokalise](https://lokalise.com/). I can send an invite to join the Aerial Views team, I just need an email address - which you can send privately if you like?

OK, we can have a try. This is my email address: juneix#outlook.com

**Comment by theothernt** [comment]
> OK, we can have a try, I will try to translate the software into Simplified Chinese.

Invite sent!

**Comment by juneix** [comment]
> > OK, we can have a try, I will try to translate the software into Simplified Chinese.
> 
> Invite sent!

I have translated the application settings interface into simplified Chinese, mainly the content of the “strings.xml” file, right? As for the video description, I think Apple's official video already supports simplified Chinese by default. Looking forward to updating the new version that supports simplified Chinese!

**Comment by theothernt** [comment]
Thank you for the translations. Although strings.xml contains most of text, arrays.xml contains the rest. Also, comms1_strings.json and comm2_strings.json contain the text for the community videos (nearly 40 in total)

**Comment by theothernt** [comment]
Ok, I've filled in a few entries and hide some unnecessary ones - there is about 120 entries left when you have time 😅

**Comment by theothernt** [comment]
Thank you so much for all that translation work. I hope to have the update live in the next day or two.

Also, in the release notes - should I use your a) real name or b) GitHub username ?

**Comment by juneix** [comment]
> Thank you so much for all that translation work. I hope to have the update live in the next day or two.
> 
> Also, in the release notes - should I use your a) real name or b) GitHub username ?

It's my pleasure, thank you. Just use my username.

**Comment by theothernt** [comment]
It looks like the update will be out on Wednesday.

**Comment by theothernt** [comment]
> It looks like the update will be out on Wednesday.

Ok, v1.6.3 is now live on GitHub 🎉

**Comment by theothernt** [comment]
There are some text updates on Lokalise, did it notify you via email?

**Comment by juneix** [comment]
> There are some text updates on Lokalise, did it notify you via email?

Long time no see, I recently updated the app and discovered many great new features! However, some entries have been adjusted resulting in errors, and there are also newly added entries. I am currently revising and updating the Chinese translation these days. 

Additionally, I noticed that there are many entries about `Projectivy Launcher` and `Amazon Videos` in the `Lokalise` translation project. Are they prepared for later versions? My TV has been modified by the manufacturer and is not a native Android TV system. I have installed Projectivy Launcher (which I have not used before) but have not seen any related settings.

**Comment by theothernt** [comment]
Thanks for coming back!

Yes, a lot of new features have been added on the last year. I have tried to update the translations using the suggestions from Google or DeepL - apologies if some are wrong!

The Projectivy features and Amazon videos are new. They are available in the public beta from the Play Store. But I hope to release them in the next version due in a week or two.

**Comment by juneix** [comment]
> Thanks for coming back!
> 
> Yes, a lot of new features have been added on the last year. I have tried to update the translations using the suggestions from Google or DeepL - apologies if some are wrong!
> 
> The Projectivy features and Amazon videos are new. They are available in the public beta from the Play Store. But I hope to release them in the next version due in a week or two.

OK, the Chinese manufacturer's TV does not have Play Store, but I have added AerialViews beta to my phone. I will experience the new features and adjust the translation, which will be completed in about two or three days.

**Comment by theothernt** [comment]
Thanks, I am uploading a new beta today but I can update the translations next week for the full release.

**Comment by theothernt** [comment]
Have you had a chance to look at the translations, let me know if you need more time?

EDIT: I see you made the changes on Saturday, 3 days ago, so I'll take those updated translations and release the app. Thanks again!
