### ISSUE TITLE
Microsoft's Wallpapers

### ISSUE THREAD

**Issue by jmlugones** [theothernt/AerialViews#135]
Hello. With the new update and photo support, online wallpaper catalogs could be accessed. I know Microsoft has a collection that they update daily, they use them for Windows 10, 11, Edge and Bing. I use the following link to download them and add them to my personal collection:

https://www.wallpaperhub.app/

There is also the following website:

https://interfacelift.com/wallpaper/downloads/downloads/any/

It has thousands of wallpapers shared by its own photographers. Those two are the ones I use for my collection, but there are plenty more. And in the future add these collections to AerialViews. It may be an option for those who use a data plan, or have a low connection speed.

Your work is great as always, congratulations and thank you. Greetings.

**Comment by theothernt** [comment]
I do plan to add sources for photos, I'll probably start with Unsplash as they have an API and a flexible license.

As for the links above, there is no way for the app to use those images unless you download them yourself.
