### ISSUE TITLE
Bottom of video distorted on mp4 videos.

### ISSUE THREAD

**Issue by 1upmushroom** [theothernt/AerialViews#136]
I was using my own videos to play during the screen saver and they have a weird screen issue on the bottom of the screen.

I'm using a Nvidia Shield Pro with the latest updates. Here are some pictures of what I am seeing.

https://imgur.com/a/9o7kVIx

Here is the video file that was playing.
https://files.catbox.moe/7gnun8.mp4

I converted the files with Handbrake 480p H.264 mp4.

This is happening on all videos.  Could this be because the format is 4:3?

**Comment by theothernt** [comment]
It might be related to the video being 4:3 as another user had a similar issue.

Would it be possible to try a) other 4:3 videos or b) a higher quality version of that episode?
