### ISSUE TITLE
Bug - missing return statement

### ISSUE THREAD

**Issue by Andres78** [theothernt/AerialViews#138]
It's seems like here was skipped 'return' statement:
https://github.com/theothernt/AerialViews/blob/5069bced627eba43b57595e5a08a6e35303a2424/app/src/main/java/com/neilturner/aerialviews/providers/SambaMediaProvider.kt#L83

**Comment by theothernt** [comment]
Thank you for finding that bug, I've made a fix to the code.

Is it ok to mention your username in the release notes of the next update?
