### ISSUE TITLE
Changing sleep timer on Fire TV

### ISSUE THREAD

**Issue by Devon2000blue** [theothernt/AerialViews#139]
Hi just wanted to say I love your work, the commands on my firestick worked likeva charm, thank you. Is there a command that let's you extend aerial views longer than 15 min? It seems like after 15 min the screen goes to sleep.

**Comment by theothernt** [comment]
Typically that's a setting within the settings menu - as a screensaver can't make a Fire TV or Android TV device sleep, as far as I know.

On Google TV, I can set when the device sleeps in the settings menu. If something like that doesn't exist on Fire TV, I can probably find an ADB command for it?

**Comment by Devon2000blue** [comment]
I just wanted to say thank you for responding to my messages. 
There is no setting on the fire tv for this, I would really appreciate it if you can find a abd command, that would be awesome, thank you again sir.

**Comment by theothernt** [comment]
No problem, [I found an article that lists two commands you can use](https://www.aftvnews.com/how-to-set-custom-sleep-or-screensaver-times-on-the-amazon-fire-tv-or-stick-without-root/)...

`settings put secure sleep_timeout 123456789`

and

`settings put system screen_off_timeout 123456789`

Just replace `123456789` with the time you want. 30 minutes is `1800000`, for example

**Comment by Devon2000blue** [comment]
Thank you, I'm going to expirament with this right now.

**Comment by theothernt** [comment]
> Thank you, I'm going to expirament with this right now.

Ok, let me know how you get on!
