### ISSUE TITLE
Looping videos without fade in/out effect

### ISSUE THREAD

**Issue by fail2ban1337** [theothernt/AerialViews#140]
I was wondering if there's a way to loop the videos played by AerialViews. Currently, the videos play once. I'd like them to loop seamlessly so that they continue to play in a loop without interruption.

Is there a setting or a way to implement this feature? If it's not currently supported, would it be possible to consider adding this feature in a future update?

Thank you for your time and consideration. Looking forward to your response!

**Comment by theothernt** [comment]
Aerial Views works by making a playlist of videos. This playlist does loop eventually but each video is only played once until it does.

Even if you have a playlist of *1* video, which would give you a looping video, you will see the video fade out when it ends only to fade back in again and start.

**Comment by fail2ban1337** [comment]
Thank you for clarifying how AerialViews currently handles video playback.

Would it be possible to consider implementing an option to loop a single video without the fade effects? I believe this feature would be a valuable addition for many users.

Thanks again for your explanation and consideration!

**Comment by theothernt** [comment]
Yes, that's possible and something I've been thinking about for a while. I was initially going to add options to change the fade speed (.5, 1.5, 2.5 seconds, etc) but I can also allow it to be disabled.

I assume you have videos that work well when looped, as the Apple video don't?

**Comment by fail2ban1337** [comment]
change the fade speed or disable it altogether would be a great addition to the customization features of AerialViews.

Yes, I do have some videos that loop seamlessly without any issues, and I believe many users might have similar videos they'd like to play continuously. Having the ability to disable the fade effects would allow for a smoother viewing experience for such videos.

I appreciate your consideration in implementing this feature.

**Comment by pkly** [comment]
It would be nice if you could allow looping videos until the closest time for the view to change if video is under X seconds maybe?

Something like maximum short video loop length: 1m (default), so then if the video is 53s and the view has to change in 3m it'd loop 3 times?

**Comment by aSoaked** [comment]
This feature would be very helpful for me.
I have a lot of smaller clips that loop seamlessly and would love to have each individual video repeat for 5min without fade until it switches to the next video or image.

**Comment by theothernt** [comment]
I have a beta ready, would some of you be willing to test it?

**Comment by theothernt** [comment]
Ok, [here is v1.7.2 beta2](https://www.dropbox.com/scl/fi/v39a546y59ve6vhglxzdr/aerial-views-1.7.2-beta2.apk?rlkey=435xu1bsjwwngqhcceqlzt3sc&dl=0).

* _Settings > Appearance > Transitions >_ Fade In + Fade Out timing can be changed or disabled
* For the "Loop short videos" feature, look in _Settings > Playlist_
* The "Play random segments of videos" doesn't work yet. It was suggested by someone via email.

Let me know if you spot **anything** out of the ordinary!

**Comment by aSoaked** [comment]
I did a short test and it worked well in my limited testing.
Is it possible to configure it in such a way that short videos loop for example for a total of 5min, but a 7min would play in full?

**Comment by theothernt** [comment]
Ok, [here is a new build](https://www.dropbox.com/scl/fi/9dn82oj4n69uewyatehfp/aerial-views-1.7.2-beta2.apk?rlkey=7qyzjsjtxugqrqr1wmt7sl4g3&dl=0) with that option to ignore the video limit for 'longer' videos.

Also, if you get the chance, there is a new Now Playing overlay which need some testing.

**Comment by aSoaked** [comment]
Thanks, the video limit now works perfectly for my use case.
I can have 30 second videos play for 3min and have 5min videos play for their full length ❤️ 

How can I test the now playing feature? Is it for music?
I have no music on since my display is not connected to an audio output

**Comment by theothernt** [comment]
> Thanks, the video limit now works perfectly for my use case. I can have 30 second videos play for 3min and have 5min videos play for their full length ❤️

Great, it'll be in the next release, which maybe in the next couple of weeks.

> How can I test the now playing feature? Is it for music? I have no music on since my display is not connected to an audio output

It's for music, it should show the current song + artist from what ever music app is playing in the background. If you don't play music on your device, don't worry about it.

**Comment by theothernt** [comment]
Here is [an updated beta](https://www.dropbox.com/scl/fi/cpeg8pgdz663wbm1auvg2/aerial-views-1.7.2-beta3.apk?rlkey=xk6ixk6sqexmxrpgithzrbgbi&dl=0), which should be the last before a release next week.

Here is an overview of some of the new playback features...

* Adjust fade in/out times of photos/videos - including disabling the animation all together
* Short videos can be looped within a time limit (ie. 30sec video 4 times with a 2min limit set)
* With a limit set (eg. 2mins), a random piece of a long video can be played (ie. 6-8mins as not 0-2mins)
* GIF support
* Flexible button assignment - press and long press
* Hide overlays after a timeout or always hide - reveal with button press option.

Let me know if you have a) any questions or b) find any issues at all, any unexpected behaviour!

**Comment by theothernt** [comment]
v1.7.2 is now out, if you're running a beta - please update! thanks.
