### ISSUE TITLE
ADB : screensaver timeout on Sony A95L

### ISSUE THREAD

**Issue by visualight** [theothernt/AerialViews#141]
I have a Sony A95L television with Google TV (android 12). I used ADB to change the screensaver timeout: 120000 (2 minutes). This does not work: the sreensaver launches after 5 minutes. Do you have an idea ? THANKS

**Comment by theothernt** [comment]
This is just a guess, but it's possible that newer Google TVs (and devices) don't let you set the screensaver below 5 minutes.

To test this, I would use the ADB command to set a timeout of 420000 (7 minutes). See if that works. Then try 360000 (6 minutes)... then 240000 (4 minutes).

Also, to confirm is the ADB command are being set properly, you can use `settings get system screen_off_timeout`

**Comment by visualight** [comment]
Thank you for your reply. you are right: the new Sony TVs cannot go below 5 minutes to activate the screen saver. This is very problematic especially for Oled televisions. For me it is a hidden attempt at sabotage to encourage slab marking and therefore push customers to buy new equipment more quickly. Or maybe Sony has nothing to do with it and it's a limitation of Google TV. If this is the case Google TV is not a system suitable for OLED televisions. In short, if you have an additional solution (under the hidden override option in the ADB console), I'm interested!

**Comment by theothernt** [comment]
Quick question - is the Sony A95L a 2023 model TV?

**Comment by visualight** [comment]
Yes

**Comment by theothernt** [comment]
I did some more research on the model of TV you have. It seems that although OLEDs can suffer from burn-in, the problem is much less likely on modern TVs thanks to a) better panels and b) software mitigation (when the TV is in standby, for example).

So having a minimum timeout of 5 minutes, although strange, shouldn't cause any issues with your TV. I do think this decision was made by Sony, I just have no idea why.

**Comment by visualight** [comment]
Thank you very much for your reply. Obviously, and given that QDOLED is still basic OLED, I fear that the marking problem will appear. 

According to my research, the problem affects not only Sony but all new android 12 TV's. It seems to be a new limitation from Google (seen on Reddit).

If you have time, it would be nice to develop a system application (which remains active all the time) with its own Time Out to automatically trigger the screensaver when inactivity is detected. 

This would be a great add-on for your screen saver, or even a great opportunity for a paid pro feature.

Ideally, a separate apk would also be welcome. 

Have a nice day! 

Raphaël

**Comment by theothernt** [comment]
> If you have time, it would be nice to develop a system application (which remains active all the time) with its own Time Out to automatically trigger the screensaver when inactivity is detected.
> 
> This would be a great add-on for your screen saver, or even a great opportunity for a paid pro feature.

I'll do a bit of research and see what I can find, but it may have to be a separate app due to the permissions required to run!
