### ISSUE TITLE
Video playback speed toast always shows settings speed.

### ISSUE THREAD

**Issue by dog77k** [theothernt/AerialViews#142]
When I change the current playback speed the d-pad up and down, the speed actually changes, but the toast message always shows the preferences setting speed, not the actual current speed.

It seems like the fix would be something like changing "GeneralPrefs.playbackSpeed" to "videoPlayer.playbackSpeed" in handlePlaybackSpeedChanged() of ScreenController.kt

**Comment by theothernt** [comment]
Thanks for spotting that, it'll be fixed in the next release.

Given that the app handles images now, do you think I should ignore d-pad up/down when an image is being displayed ie. you can only change the playback speed while a video is playing?

**Comment by dog77k** [comment]
Yeah, good call.  Either ignore or possibly change the slideshow speed if a
picture is displayed.

**Comment by theothernt** [comment]
It looks like any speed change made was not being saved. By simply saving the change, the toast is correct.

So, if you have playback speed set to 1x. Start the screensaver, increase speed to 2x, exit the screensaver. Either check the Playlist prefs or start the screensaver again and it should be at 2x.
