### ISSUE TITLE
Addition Scaling Options to Prevent Cropped Images

### ISSUE THREAD

**Issue by bobbytables2048** [theothernt/AerialViews#145]
I'm using this to display photos and videos over a network share using a Shield TV. I have found that the current image scaling options are limited and I end up with either cropped photos when using Fill or cropped videos when using Center.

Is it possible to add a scaling option which will shrink or enlarge the photo/video adding black bars to the top/bottom or left/right of the image? Black could also be replaced with something matching the image, like a common color or a technique similar to "photo gallery and screensaver" which zooms, blurs and dims the image to use as the background.

**Comment by theothernt** [comment]
Image support was only added in the last update and it's pretty basic. I do hope to add more features like you're suggesting but it will take a few months. I will update you on progress though.

**Comment by theothernt** [comment]
The current version, v1.7.2, does have a 2nd option which should scale the images to fit the screen but it WON'T crop them. Let me know if that's working for you. 

I'll be updating the description of each option in the next update to make it clearer what it does.

**Comment by theothernt** [comment]
Yes, it should be possible. I'll have to do some research and see how easy (or not) it is to implement. I'll report back when I have more info...

**Comment by theothernt** [comment]
Blur is now available in the latest public beta for testing.
