### ISSUE TITLE
Allow the `Loading...` text to be hidden

### ISSUE THREAD

**Issue by pkly** [theothernt/AerialViews#147]
**Describe the solution you'd like...**

It doesn't seem possible right now and seems rather easy to implement? The text is distracting and I'd like the screensaver to not display it if possible.

**Comment by theothernt** [comment]
This feature is actually in the next version, v1.7.1, which is due for release in the next day or so.

**Comment by theothernt** [comment]
Ok, 1.7.1 is out - enjoy a 'textless' startup 😅
