### ISSUE TITLE
No audio when "mute videos" option is unchecked

### ISSUE THREAD

**Issue by stillrinzler** [theothernt/AerialViews#148]
**What were you trying to do...**

I'm trying to play audio for the videos that are being played

**And what actually happened (ie. describe the bug)...**

When I uncheck the option, it doesn't play audio for the videos, I tried arc and bluetooth but there was no audio

**What kind of device do you have? (eg. Nvidia Shield, Sony TV, etc)...**

I used the MI Box 4K with a Philips tv

**Comment by theothernt** [comment]
If you're talking about the videos included with Aerial Views (ie. Apple and Community videos), then they don't have sound - all the videos are silent.

**Comment by stillrinzler** [comment]
> If you're talking about the videos included with Aerial Views (ie. Apple and Community videos), then they don't have sound - all the videos are silent.

Ohh got it, you've gotta any recommendations for videos with audio that is similar to Apple and community ones?

**Comment by theothernt** [comment]
Currently, all the videos I use (ie. extra ones, like my own drone footage) are all silent as well.

One thing that came to mind - if you find a video you like with music on YouTube, you could use a utility like [yt-dlp](https://github.com/yt-dlp/yt-dlp) to download the video?
