### ISSUE TITLE
Breaking the location title in two lines

### ISSUE THREAD

**Issue by stillrinzler** [theothernt/AerialViews#149]
Is it possible to break the location in two lines as for some videos since the name of the location is so long and it overlaps with the time

**Comment by theothernt** [comment]
It's not possible to break the description text over two lines. I'm hoping to fix this in a future release.

For the moment, the only two options are to either a) reduce the text size or b) move the description to a row on its own so it has more space.

**Comment by stillrinzler** [comment]
Cool, ohh okay

**Comment by theothernt** [comment]
Out of curiosity, did you happen to make the text size bigger or just have a long message on one side, then the location on the other?

**Comment by stillrinzler** [comment]
> Out of curiosity, did you happen to make the text size bigger or just have a long message on one side, then the location on the other? 

I've made it bigger cuz the text was small
