### ISSUE TITLE
Add language support

### ISSUE THREAD

**Issue by dikodahan** [theothernt/AerialViews#150]
Hi,

I am interested in adding another language to the app. How can I get access to the localization platform?

**Comment by theothernt** [comment]
I just need a) an email address and b) the language you'd like to translate to.

Also, as v1.7.1 is just out - any translation changes won't appear until to next version of the app which maybe a couple of months away.

**Comment by dikodahan** [comment]
diko.dahan@gmail.com

**Comment by theothernt** [comment]
> diko.dahan@gmail.com

Ok, invite sent. Is it ok to use Arabic (ar) as opposed to some other variation?

**Comment by dikodahan** [comment]
I got the invite, though I don't understand how the Arabic is tied here?
Hebrew and Arabic are two separate languages, though both are right-to-left, which is where the similarities end :)

**Comment by theothernt** [comment]
> I got the invite, though I don't understand how the Arabic is tied here? Hebrew and Arabic are two separate languages, though both are right-to-left, which is where the similarities end :)

Apologies, that was my stupid mistake - I've set the language to Hebrew now 😅

**Comment by theothernt** [comment]
I see that you've completed the translation - thank you so much for that!

As the next release might be a month or two away, I can make a new build of v1.7.1 for you that includes the Hebrew translation if you'd like?

**Comment by dikodahan** [comment]
Thank you, and no need.
It can wait for the next release. No rush.

**Comment by theothernt** [comment]
The Apple videos are already translated in many languages. I assumed Hebrew was covered, but I was wrong. So I've added the Apple strings/text to Lokalise to be translated.

Also, are the Google/MS translation suggestions any good?

**Comment by dikodahan** [comment]
The translation has some misses here and there.
I'll work through them and finish it.

**Comment by dikodahan** [comment]
Done

**Comment by theothernt** [comment]
> Done

Thanks again, that's been integrated into the app.
