### ISSUE TITLE
URI to launch application (part 2)

### ISSUE THREAD

**Issue by bigeazy000** [theothernt/AerialViews#151]
Hello,

First, thank you for this amazing app! I see there was a request to add a deep link URL (issue #122). Has this been implemented? The use case is trying to launch AerialViews from wall panel app as a screensaver.. Any help/feedback would be greatly appreciated!

**Comment by theothernt** [comment]
At the time it wasn't implemented because Android Intents worked - plus I did try to implement Deep Links but it didn't seem to work for me.

I've read that Deep Links only work on Chrome, which you'd have you sideload. Can you give me some examples of how it will be used or is used in other apps?

**Comment by bigeazy000** [comment]
Hi, thanks for the quick response! I am using an app called wallpanel (https://github.com/TheTimeWalker/wallpanel-android) to load an webpage in a kiosk-like mode, like an HA dashboard for example. I would like to run AerialViews after 'x' minutes of inactivity in Wallpanel. The app has an option to set "Web Screensaver URL." This is where I would like to load AerialViews as a screensaver. Hopefully this makes sense, let me know if you have more questions..

**Comment by theothernt** [comment]
I just had a quick look at WallPanel, and specifying a deep link URL probably won't work.

From what I can tell, when you enter a URL to call after a timeout - it tries to set the webpage of the browser (WebView) to that - that will not invoke a deep link. You may want to confirm with the developer though.

**Comment by theothernt** [comment]
And just as I finished writing that, I searched the source code... [it appears the docs tell you how to call Intents directly](https://wallpanel.xyz/docs/launch-external-apps).

intent:#Intent;launchFlags=0x10000000;component=com.neilturner.aerialviews/.ui.screensaver.TestActivity;end

**Comment by theothernt** [comment]
Hmmm... this might not be for the screensaver URL, so contacting the dev might be the best option?

**Comment by bigeazy000** [comment]
ok, I'll do that, but this helps a lot.. Thanks again!

**Comment by theothernt** [comment]
I just had another look at the code and did some testing. The 'intent' I mentioned above, it will only work if it's a link in a webpage that's clicked.

So for the screensaver, you'd have to make a blank webpage, make the webpage redirect to another page on load (ie. the intent text above), that might work.

Obviously, this would be easier if the Settings had a "Screensaver Intent" option, so I'll suggest that as a feature I can contribute to the app.

**Comment by theothernt** [comment]
@bigeazy000 did you get anything working?
