### ISSUE TITLE
After update SMB stopped working

### ISSUE THREAD

**Issue by monogoat** [theothernt/AerialViews#153]
I am using a Chromecast w/ GoogleTV (older version, not the new 4k one) to display a slideshow sourced from a SMB share provided by Unraid with a guest login. It has been working fine, but this morning it said it couldn't find anything to display. I tried to test the server connection and it said that server authentication failed so I tried to add the root credentials as a test and it then said something like it couldn't find the share.

I pulled up the github and noticed 1.7.1 is very recent so I checked my version and it had updated through the play store. I uninstalled it and installed 1.7.0 from here and the SMB connection works fine again.

I don't have time to updated it to 1.7.1 to see if it breaks again, but there may be an issue with the new update.

**Comment by theothernt** [comment]
Thanks for reporting the issue. Aerial Views v1.7.1 contains an update to the 3rd party SMB library - that's likely the problem.

If you don't mind, can you try a few things to see if we can fix this...

1. Are you using SMB v3 or v2 on the server?
2. Can you try each of the `Samba > Select SMB dialects` to see if any then work?

**Comment by monogoat** [comment]
Unraid is the latest version (6.12.3) and I don't have any particular version of SMB forced on the server, and both netbios and wsd are enabled to it should support all (v1, v2, and v3) I believe.

I tried disabling all of the V2 dialects before rolling the version back, but after I close the office this evening I can updated it back to 1.7.1 and try each one individually.

**Comment by theothernt** [comment]
Also, I forgot to ask, is your guest account username 'guest' with no password?

**Comment by kj4z** [comment]
I am experiencing the same issue.  My server is samba, version `4.15.13-Ubuntu` with stock configuration.  I found that I had to uncheck/disable all v3 dialects to get AerialViews to work again.  With only v2.0.2 and v2.1 checked, it works.

**Comment by theothernt** [comment]
> I am experiencing the same issue. My server is samba, version `4.15.13-Ubuntu` with stock configuration. I found that I had to uncheck/disable all v3 dialects to get AerialViews to work again. With only v2.0.2 and v2.1 checked, it works.

Thanks for the info. Were you also using a guest account?

**Comment by kj4z** [comment]
> > I am experiencing the same issue. My server is samba, version `4.15.13-Ubuntu` with stock configuration. I found that I had to uncheck/disable all v3 dialects to get AerialViews to work again. With only v2.0.2 and v2.1 checked, it works.
> 
> Thanks for the info. Were you also using a guest account?

Yes.  The files are located on a share with anonymous access, and username and password are blank/not set.

**Comment by monogoat** [comment]
Same in my case, blank username and password. I had to leave early yesterday so I haven't had time to update it again and mess with the dialects on mine.

**Comment by theothernt** [comment]
@monogoat hopefully changing the dialects will fix your issue too.

Either way, I will be testing Ubuntu and Unraid (installed in a VM) tomorrow.

**Comment by Mr-HaleYa** [comment]
I had the same issue after the update.

Unraid 6.12.10
SMB settings all default.
Folder share settings set to public no username no password, has been working for over a year.

Disabled all dialects v3 and above and now works.

**Comment by theothernt** [comment]
Thanks for the info @Mr-HaleYa. It appears there was a change in the library I use (SMBJ) that causes this.

I will update the app so that the default is the use the Samba v2 protocol for new users.

As I'm not a Samba protocol expert, I'm trying to find out why a Samba server supporting v2 and v3 will reject "anonymous" accounts when the v3 protocol is used.

Also - just to mention it to everyone - it's **not** recommended to use Guest or Anonymous (no username/password) accounts for security reasons.

**Comment by monogoat** [comment]
I finally had time to play with it, and I can confirm the same solution works on mine. Let me know if you want this issue closed or left open while you figure out the protocol change.

**Comment by theothernt** [comment]
In the next release, the app will default to using Samba v2.x protocols - that should be enough for the moment.

**Comment by Plazzmex** [comment]
Hi,

I have the same problem with the latest 1.7.1 version.
Using Windows 10 with the latest updates as an SMB server, with shared folder for guest (Anonymous connection) for aerial files.
In 117.1 No matter which SMB dialect I choose in the settings, it says "Authentication failed".
Rolling back to version 1.7.0 fixes it and it works perfectly.

**Comment by theothernt** [comment]
> I have the same problem with the latest 1.7.1 version. Using Windows 10 with the latest updates as an SMB server, with shared folder for guest (Anonymous connection)

I only have Windows 11 to test with but I'll see what I can find.

Also, what you say 'guest', do you mean username: guest with no password?

**Comment by theothernt** [comment]
> > Also, what you say 'guest', do you mean username: guest with no password?
> 
> No, I mean that everyone on the network can access it without login details. In the app, the username and password are blank.

Do you remember how that was setup?

So far, I've enabled the built-in Guest account, add Guest user to the shared folder, "File and printer sharing" is enabled in Settings and I can access the shared folder using the username 'guest'.
