### ISSUE TITLE
Text fade out

### ISSUE THREAD

**Issue by KselaGit** [theothernt/AerialViews#154]
Is it possible to add an option for text to fade out a few seconds after the video starts? For example, the description of the video appears as the video starts and fades out a few seconds after.

**Comment by theothernt** [comment]
Yes, I hope to add a feature like that in the next couple of releases.

It should also be paired with a feature to hide all overlays unless the d-pad is pressed.

**Comment by KselaGit** [comment]
> Yes, I hope to add a feature like that in the next couple of releases.
> 
> It should also be paired with a feature to hide all overlays unless the d-pad is pressed, which was requested quite a while ago.

Yeah, Id like to have no overlay but also be able to see what place the screensaver is showing, maybe even the time.

**Comment by theothernt** [comment]
[There is a beta](https://github.com/theothernt/AerialViews/issues/140#issuecomment-2322919161) if you'd to try that feature out before release. If not, the update should be out for general release in the next week or two.

**Comment by KselaGit** [comment]
> [There is a beta](https://github.com/theothernt/AerialViews/issues/140#issuecomment-2322919161) if you'd to try that feature out before release. If not, the update should be out for general release in the next week or two.

Just installed it. Animation time setting doesn't seem to do anything at the moment for either overlay or videos. Even the disable option doesnt turn them off.

**Comment by theothernt** [comment]
> > [There is a beta](https://github.com/theothernt/AerialViews/issues/140#issuecomment-2322919161) if you'd to try that feature out before release. If not, the update should be out for general release in the next week or two.
> 
> Just installed it. Animation time setting doesn't seem to do anything at the moment for either overlay or videos. Even the disable option doesnt turn them off.

Do you mean Settings > Appearance > Animation > Auto hide overlays?

Setting it to '6 seconds' would be the overlays would be visible at the start of a video/photo but disappear after 6 seconds.

**Comment by KselaGit** [comment]
> > > [There is a beta](https://github.com/theothernt/AerialViews/issues/140#issuecomment-2322919161) if you'd to try that feature out before release. If not, the update should be out for general release in the next week or two.
> > 
> > 
> > Just installed it. Animation time setting doesn't seem to do anything at the moment for either overlay or videos. Even the disable option doesnt turn them off.
> 
> Do you mean Settings > Appearance > Animation > Auto hide overlays?
> 
> Setting it to '6 seconds' would be the overlays would be visible at the start of a video/photo but disappear after 6 seconds.

I mean Settings > Appearance > Animation > Overlay animations and Video & photo animation settings doesnt do anything. Whatever I set it to, 200ms or 2000ms or disabled, it stays the same.

**Comment by theothernt** [comment]
> > > > [There is a beta](https://github.com/theothernt/AerialViews/issues/140#issuecomment-2322919161) if you'd to try that feature out before release. If not, the update should be out for general release in the next week or two.
> > > 
> > > 
> > > Just installed it. Animation time setting doesn't seem to do anything at the moment for either overlay or videos. Even the disable option doesnt turn them off.
> > 
> > 
> > Do you mean Settings > Appearance > Animation > Auto hide overlays?
> > Setting it to '6 seconds' would be the overlays would be visible at the start of a video/photo but disappear after 6 seconds.
> 
> I mean Settings > Appearance > Animation > Overlay animations and Video & photo animation settings doesnt do anything. Whatever I set it to, 200ms or 2000ms or disabled, it stays the same.

Thanks, it seems there are issues with some of the animations.

1) Fade In for videos/photos might be incorrect
2) 'Disabled' seems to be broken.

Also, if you happen to have Developer Mode enabled and the 'animation scale' has been changed, this will interfere with animations in the app.

**Comment by KselaGit** [comment]
> > > > > [There is a beta](https://github.com/theothernt/AerialViews/issues/140#issuecomment-2322919161) if you'd to try that feature out before release. If not, the update should be out for general release in the next week or two.
> > > > 
> > > > 
> > > > Just installed it. Animation time setting doesn't seem to do anything at the moment for either overlay or videos. Even the disable option doesnt turn them off.
> > > 
> > > 
> > > Do you mean Settings > Appearance > Animation > Auto hide overlays?
> > > Setting it to '6 seconds' would be the overlays would be visible at the start of a video/photo but disappear after 6 seconds.
> > 
> > 
> > I mean Settings > Appearance > Animation > Overlay animations and Video & photo animation settings doesnt do anything. Whatever I set it to, 200ms or 2000ms or disabled, it stays the same.
> 
> Thanks, it seems there are issues with some of the animations.
> 
> 1. Fade In for videos/photos might be incorrect
> 2. 'Disabled' seems to be broken.
> 
> Also, if you happen to have Developer Mode enabled and the 'animation scale' has been changed, this will interfere with animations in the app.

"Fade In for videos/photos might be incorrect" 
-Same is also the case for overlay fade in/out but the overlay timeout works fine

Dont have animation scale changed in dev settings.

**Comment by theothernt** [comment]
Ok, the download link has been updated as I found the issue - thanks for all the testing and feedback so far, I can't believe I missed that bug!

**Comment by KselaGit** [comment]
Seems to be working fine now. Thank you for a quick response on the bugs!

**Comment by theothernt** [comment]
v1.7.2 is now out, if you're running a beta - please update! thanks.
