### ISSUE TITLE
Please add weather support 

### ISSUE THREAD

**Issue by steve51184** [theothernt/AerialViews#155]
please add wether support it'd look so cool when the screen saver is on the to see the weather next to the time etc

**Comment by theothernt** [comment]
This feature [was requested previously](https://github.com/theothernt/AerialViews/issues/36).

Keep an eye on that issue for updates.

**Comment by theothernt** [comment]
v1.7.8 is out now on GitHub with the Weather overlay. Expect the Play Store version in a few days.
