### ISSUE TITLE
Connect Aerial Views to Windows network drive?

### ISSUE THREAD

**Issue by TBOTO** [theothernt/AerialViews#156]
I'm not a super technical person but is there a way to get aerial views to connect to a shared network drive from my Windows computer?
it if so could someone point me in the direction of the instructions on how to do this?

**Comment by TBOTO** [comment]
Solved it 

1: create shared folder on windows
2: open command terminal type ipconfig to get computer    ip address 
3: then enter details into Aerial Views
3a: 
Hostname = ip address 
Share Name = /Your Folder
Username = your windows computer username where you created shared folder
Password = your windows computer password where you created shared folder
4: good to go!

**Comment by theothernt** [comment]
Glad you got it sorted. Let me know if you have any other questions!

Also, is there anything else I can do to make it easier for others - maybe link to a guide, etc?

**Comment by TBOTO** [comment]
Hello,
yes, definitely a link to a guide.
Thank you
