### ISSUE TITLE
Gif support

### ISSUE THREAD

**Issue by pkly** [theothernt/AerialViews#157]
**Describe the solution you'd like...**

Simple gif playback on repeat (treated as image).
I've added a gif or two into my smb share but I've not seen them show up at all, which makes me think that gif support is not enabled. It probably shouldn't be too much work, so could you look into it?

**Comment by theothernt** [comment]
It looks like the library I use for displaying images also supports animated GIFs, so that'll be enabled in the next release!

**Comment by theothernt** [comment]
If you'd like to test GIF playback, it's enabled in [this new beta](https://github.com/theothernt/AerialViews/issues/140#issuecomment-2322919161).

As GIFs are treated as images, not videos, if the "slideshow speed" is set to 30 seconds, the GIF will look endlessly withing that time. I may need to add more options to this in future, let me know what you think!

**Comment by theothernt** [comment]
v1.7.2 is now out, if you're running a beta - please update! thanks.

**Comment by theothernt** [comment]
I've just made some updates to the library that handles images + GIFs in v1.7.5 - if anything is broken, please let me know.

**Comment by theothernt** [comment]
Damn, looks like I broke GIF playback in v1.8.2 btw - it'll be fixed in the next update and/or public beta.
