### ISSUE TITLE
Black screen on Bravio VU1

### ISSUE THREAD

**Issue by iamhazel** [theothernt/AerialViews#158]
**What were you trying to do...**
Use the app as intended

**And what actually happened (ie. describe the bug)...**
The clock and stuff appears but no video, just a black screen. It's weird because it worked fine the first couple times before breaking. But I don't think I changed anything.

**What kind of device do you have? (eg. Nvidia Shield, Sony TV, etc)...**
Sony Bravia VU1

**Comment by iamhazel** [comment]
Actually today it's working so closing. Thanks for the awesome app!

**Comment by iamhazel** [comment]
Actually today it's working so closing. Thanks for the awesome app!

**Comment by theothernt** [comment]
If anything like that happens again, do let me know!
