### ISSUE TITLE
Tap to exit screensaver

### ISSUE THREAD

**Issue by geroulas** [theothernt/AerialViews#159]
Add support for just tapping the screen to exit the screensaver.
I use this for my walk mounted Tablet and the only way I can exit the screen saver is by pushing the time button. 

I don't know if this is how is supposed to work or there is something with with my settings. 
I have it installed on a Lenovo M11 tab, Android 14.

**Comment by theothernt** [comment]
A couple of questions for you...

1. Can you try another screensaver and see if it exists when you tap the screen?
2. If I add this as an option, would you be willing to test a beta APK?

**Comment by theothernt** [comment]
Any update @geroulas ?
