### ISSUE TITLE
Adb: not found (Google Tv)

### ISSUE THREAD

**Issue by rbhalla13** [theothernt/AerialViews#168]
When I try to connect to my IP it says : ~ash:adb: not found.

been trying to have these screensavers on my tv since forever 😭

**Comment by theothernt** [comment]
1. What Google TV device or TV are you using?
2. Have you enabled Developer Mode on the device?
3. How are you trying to connect to the device, with a phone or PC?

**Comment by rbhalla13** [comment]
1. It’s Hisense U6K with Google TV (Android 11, RTT2.220118.001)
2. Yes, developer mode is on.
3. I am trying to connect with my iphone

**Comment by rbhalla13** [comment]
It worked!!

**Comment by theothernt** [comment]
> It worked!!

Glad to hear! is everything setup and working okay now? 🥳

**Comment by rbhalla13** [comment]
Yes, it’s working well! Is there an option to have a weather widget in there as well?

really appreciate all your hard work!

**Comment by theothernt** [comment]
> Yes, it’s working well! Is there an option to have a weather widget in there as well?

I'm hoping to have that in future, before the end of the year!
 
> really appreciate all your hard work!

Thanks, enjoy the views 😊
