### ISSUE TITLE
Videos are laggy/choppy

### ISSUE THREAD

**Issue by djoole** [theothernt/AerialViews#170]
Hi,
I’m on a Sony XH900 TV, Android 10, version 1.7.2
I never had any problem, but since a few days, all the videos (from the 3 internet sources) are very laggy. 
i tried to change 4K to 1080p but its the same. 
inassume something changed with 1.7.2, and don’t know how to rollback to 1.7.1

**Comment by djoole** [comment]
Sorry for the useless ticket… I’ve cleared the cache and it all works again perfectly. I should have thought about that about posting!

**Comment by theothernt** [comment]
No problem at all.

There were a lot of changes between 1.7.1 and 1.7.2 - including the video player itself - but I can't explain how clearing the cache would do anything ?!

If you notice anything odd - feel free to report it
