### ISSUE TITLE
Allow for more granular audio control for videos

### ISSUE THREAD

**Issue by pkly** [theothernt/AerialViews#173]
As the title states. Currently it's only on/off. Would be great if it could be changed into a slider from 0 to 100, maybe in 5% steps? 

Reason being my volume is comfortable for normal use. The videos on screensaver have audio sometimes but they don't require my full attention and I'd sometimes prefer to keep the volume on, but lower it.

**Comment by theothernt** [comment]
That makes sense, I'll add that for the next release!

**Comment by theothernt** [comment]
I've added a [beta here if you'd like to take a look](https://github.com/theothernt/AerialViews/issues/101#issuecomment-2405634028). If not, I expect the feature to be released in the next week or two.

**Comment by pkly** [comment]
I would try it but installing apks on the tv is a pain, it'd be better if you'd maybe add a beta feature for google play, so it could just install

**Comment by theothernt** [comment]
If it's any trouble, don't worry about it - I sometimes ask people, but it's not necessary as I do some testing myself as do others. Either way, it'll be out soon.

Also, I will look into the Google Play beta feature.

**Comment by theothernt** [comment]
v1.7.3 has just been released on GitHub with this feature, it should appear on the Play Store in a few days assuming no issues.

**Comment by theothernt** [comment]
I just thought of something. So, if the video has found, when the video is about the end - it should fade out visually but the sound doesn't, it would stop suddenly - is that the case?

**Comment by theothernt** [comment]
Video sound fade in/out is being added.
