### ISSUE TITLE
Optional background audio?

### ISSUE THREAD

**Issue by edinmusic** [theothernt/AerialViews#177]
Hello,

As in title, optional background audio would be a great option for multiple situations, for example:

- General usage - why not?
- Specific (niche?) usage: In EU most soundbars power off in case there isn't any audio signal in about 15 minutes. So when your TV stays idle for too long, your soundbar powers off. And some TVs don't turn them on when TV stops being idle. So if screensaver had any kind of audio, this wouldn't happen. Also in combination with #173 you could set it to very low volume.

Thanks for a great screensaver app.

**Comment by theothernt** [comment]
This feature will be in the next public beta for testing, then the next full release of the app.
