### ISSUE TITLE
Not working of fire tv cube 3rd gen.

### ISSUE THREAD

**Issue by xexets** [theothernt/AerialViews#182]
**What were you trying to do...**

auto start the app as screensaver

**And what actually happened (ie. describe the bug)...**

I followed the instructions for manual install.
In adblink -> timers I cannot set the screensaver to on.
In fire tv settings I cannot turn on the screensaver.
If I put it on ‘never’ in fire tv settings the screensaver never starts
If I put 5 minutes after 5 minutes the screensaver never goes black instead of starting aerial views screensaver.

**What kind of device do you have? (eg. Nvidia Shield, Sony TV, etc)...**

fire tv cube 3rd gen

**Comment by theothernt** [comment]
Can you tell me what version of FireOS that device runs?

**Comment by xexets** [comment]
Yes thank you! 7.6.8.1 (latest)

**Comment by theothernt** [comment]
Would you mind giving this app a try? [TDUK screensaver manager v1.0.2](https://www.techdoctoruk.com/sdm_downloads/tduk-screensaver-manager-1-0-2/)

From what I've seen from others, FireOS 7.x should be ok for 3rd party screensavers - but there's always a chance that Amazon might lock things down. They have done this with newer devices like the Fire TV Stick 4K Max (2nd gen), [as reported by a few users](https://github.com/theothernt/AerialViews/issues/127).

**Comment by xexets** [comment]
Just tried again after a restart and TDUK just says connection failed.On 28 Nov 2024, at 23:29, Al Vise ***@***.***> wrote:﻿Thank you. I have side loaded TDUK, and started it but it hangs at ‘please make sure USB debugging is turned on’. I have ADB debugging on under developer options but that is the only option, there is no additional one for USB debugging (like the Shield has). When I hover over the ADB option it says ‘allow debugging over the network’. I think Amazon might have blocked USB debugging?On 28 Nov 2024, at 23:10, Neil Turner ***@***.***> wrote:Would you mind giving this app a try? TDUK screensaver manager v1.0.2From what I've seen from others, FireOS 7.x should be ok for 3rd party screensavers - but there's always a chance that Amazon might lock things down. They have done this with newer devices like the Fire TV Stick 4K Max (2nd gen), as reported by a few users.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by theothernt** [comment]
That's very strange, but I'm glad it worked out.

If you have other questions, etc about Aerial Views... feel free to ask. I the meantime, enjoy! 🥳
