### ISSUE TITLE
Play music in background while viewing photos

### ISSUE THREAD

**Issue by Lyrics0811** [theothernt/AerialViews#185]
It looks like there's a way that you can continue to play music in the background while the screen saver kicks in to view photos.  Is there a way to start music when the screen saver is started and displaying photos?

**Comment by theothernt** [comment]
I will look into it but I'm not sure it's possible for an app to do that.

For example, if Spotify is installed and I ask Spotify to "play" ... what will it play? and my app doesn't know what songs you've played, etc.

If you use an Android phone and the experience is different, let me know.

**Comment by Lyrics0811** [comment]
I can understand not knowing what to play.  For me, I use Aerial Views on a Shield Android TV to cycle through pictures.  When the screen saver comes on, it would be nice to have some sort of background music playing.  I was thinking that in the settings, you can chose an mp3.  In my particular case, something instrumental.  

Just thought it would be a nice feature to have, but it sounds like not many may be interested in it.

Thanks!

**Comment by theothernt** [comment]
I have had a few requests for something similar - both playing your own local music or starting a music streaming app - so it is something I'm thinking about, not sure how to do it just yet - but I'll add it to the list!

**Comment by theothernt** [comment]
This feature will be in the next public beta for testing, then the next full release of the app.
