### ISSUE TITLE
Left Button Press To Go Back

### ISSUE THREAD

**Issue by yslupdates** [theothernt/AerialViews#24]
Hey I see that the app already has the skip video feature for pressing right, could we also get a press left button option for going back to the previous view? Thank you

**Comment by theothernt** [comment]
Yes, that should be possible. I've just put it off so far as most of the work was about giving people the freedom to play videos from others sources (the backend of the app). I should have more time to spend on the other parts now (playback, playlist features, UI changes). 

I'll see if I can get it added to 0.99.1 in the next week or two!

**Comment by theothernt** [comment]
That feature is now in the codebase, keep an eye out for it in 0.99.1 which is due later next week.

And if you find any issues with the feature, feel free to re-open the issue!

**Comment by theothernt** [comment]
No problem - sorry it took so long! if you notice anything odd happening, do let me know... but I have been running this build for over a week so it should be fine!
