### ISSUE TITLE
App no longer working after update

### ISSUE THREAD

**Issue by Hotboy1987** [theothernt/AerialViews#25]
After the newest update ,, app no longer working on nvidia shield ,, I have to restart the device to make the app working and after using the device for sometime and waiting for the app to start screensaver it didn't

**Comment by Hotboy1987** [comment]
I try play videos remotely from inside the program setting and it plays normal 

Yes it ask me for permission but only for the first time ,, and videos also play from local file when I test it from inside the program setting or when I go to screensaver setting and press start now ,, but it didn't start when I left the device from it self

**Comment by theothernt** [comment]
> Yes it ask me for permission but only for the first time ,, and videos also play from local file when I test it from inside the program setting or when I go to screensaver setting and press start now ,, but it didn't start when I left the device from it self

Ok, so that's a good sign so far. It suggests that the app is working and all your videos can be seen by the app.

On the Shield, can check in Settings > Device Preferences > Screen saver and make sure that Aerial Views is selected. Also, does the 'Start now' option work?
