### ISSUE TITLE
Apple Server taking priority over Samba share

### ISSUE THREAD

**Issue by finnzz** [theothernt/AerialViews#28]
First of all thank you for this excellent fork(?) of Aerial Dream.  I was using Aerial Dream the last year, and was excited to come across your app which let's me get the 2021 videos and stream the videos locally.

I have all my videos on a Samba share.  I noticed that if I don't uncheck stream apple videos directly, that Apple servers take priority over my local Samba share.

I'd prefer to have the videos stream from my samba, and then only from Apple when the videos are missing on the Samba.

Lastly, I'm using a 2nd Gen Cube (2019) FireOS7, and everything is smooth.  For your FireTV instructions, I'd recommend breaking up the ADB command into two commands:

settings put secure screensaver_components com.amazon.ftv.screensaver/.app.services.ScreensaverService:com.neilturner.aerialviews/.ui.screensaver.DreamActivity 

settings put secure screensaver_default_component com.neilturner.aerialviews/.ui.screensaver.DreamActivity

Trying to run this as one command did not work for me.

**Comment by theothernt** [comment]
It's possible there are a couple of reasons for what you're seeing...

1. It could be a bug as I did refactor and rewrite some of the code around removing duplicates. I'll re-test that and confirm.
2. When you download the videos to your NAS, did you get the latest 2021 versions using the link on this repo?

Also, thanks for reporting a mistake with the FireTV commands, I'll update that ASAP.

**Comment by finnzz** [comment]
Yeah, I used the link you posted on main page (https://aerial-videos.netlify.app/), downloaded all the videos and left the filenames unchanged.

**Comment by theothernt** [comment]
I confirmed it's a bug on my end, and is now fixed. I'll be putting out another release by the end of the week which should have this and a few other fixes - thanks again for reporting it!

**Comment by finnzz** [comment]
Thank you for the quick turn around :). I'm glad to see you actively developing it.
