### ISSUE TITLE
Videos Freezing

### ISSUE THREAD

**Issue by sb76117** [theothernt/AerialViews#31]
- Today's release (0.99.1)
- Chromecast with Google TV
- Quality is set to 4K SDR

**Comment by theothernt** [comment]
Thanks for reporting the issue, can you answer a few more questions for me...

1. Had you used a previous version of Aerial Views before, and did it play 4K videos without issue?
2. Are you able to play 4K content on other apps (Netflix, YouTube, etc) without issue?
3. Can you try setting the quality to 1080p SDR and see if that plays ok?
3. If you have the time, can you download one 4K SDR video and play it locally?

Currently, the app doesn't tell you if there are buffering issues with a video - it's something I hope to add in future - just trying to rule that out vs playback issues or a bug in the app.

**Comment by sb76117** [comment]
1. Yes, previous version 0.99 was working correctly.
2. Yes.
3. 1080p SDR screensaver ran for 15 minutes without issue.
4. Downloaded a few 4K SDR videos from https://www.videezy.com/free-video/4k and played locally on device without issue.

I'm running it again and I'll see if it recurs at a particular time. FWIW, it just ran for 10 minutes without any problems.

**Comment by theothernt** [comment]
Ok, thanks for testing all that. 

My initial guess is that there was either some brief connection issue or an issue with the hosting (server) of the video. I've seen it happen rarely on my end, or a video takes 2+ seconds to start - and I have a fast, unlimited connection.

Do let me know if anything changes or other issues occur!

**Comment by sb76117** [comment]
Inactivity started at 1215 CST.
Screensaver kicked off at 1220 CST.
As of this comment and issue closure at 2220 CST no playback issues have occurred.
No clue what happened yesterday. Could have been a random hiccup on either my network or with the source's hosting... either way, not reproduceable.
Will reopen issue if it happens again.
