### ISSUE TITLE
Option to disable manual switching of videos

### ISSUE THREAD

**Issue by mudsloth** [theothernt/AerialViews#32]
This feature is nice, but I'd like to be able to disable the use of arrow keys to navigate entirely:

> You can now skip to the next or previous video

When the screensaver is active, I'd like _any_ button on the remote to turn it off and go back to the OS/app that it was on.

**Comment by theothernt** [comment]
Although it's enabled by default, you can turn that option off in Settings > Interface > scroll down and disable 'Skip to next or previous video'. Now any button press should exit the screensaver.

**Comment by theothernt** [comment]
No problem at all - any other questions or problems, feel free to open a new issue!
