### ISSUE TITLE
Playback issues on Khadas VIM2

### ISSUE THREAD

**Issue by Mac1962** [theothernt/AerialViews#34]
I’m having issues with aerial view on my Khadas vim2 android mini computer board I’ve got this connected to my smart tv I like this better AV then aerial dream that keeps crashing but this works ok but over time it does crashed all I get then is a black screen with the time and no screen savers I’m running android nougat 7.1.2 this is the best screen saver I have all the others are crap waste of time.

**Comment by theothernt** [comment]
Thanks for reporting the issue. I have a few questions...

1. Does that device have the Google Play Store?
2. Do other videos apps like Netflix, Disney+, etc work ok?
3. What quality of videos are you trying to play - 1080p, 4K?
4. Have you tried downloading a video and playing it locally?

**Comment by Mac1962** [comment]
1. Yes it’s got google play store.
2. I haven’t got Netflix or Disney channel but videos still work 
3. 4k videos, it’s been working and hasn’t gone off yet.
4. No I haven’t tried, but I think I know what could be doing this my tv is not compatible with 4k.

**Comment by theothernt** [comment]
Ok, so is the issue that you only see a black screen sometimes - ie. no videos play?

(btw, 4K HDR requires Dolby Vision which probably isn't support on your device as it's not official)
