### ISSUE TITLE
Feature Request: Auto-resume if network issues occur.

### ISSUE THREAD

**Issue by sb76117** [theothernt/AerialViews#35]
Issue I'm having is: I often have to reset my router and I've noticed that when I do, if the screensaver is playing, it just stays black after network is restored. If I wake up the device, the screensaver will turn on again in five minutes like normal.

Fortunately, if the screen is just black, technically my screen is still saved so no big deal.

**Comment by theothernt** [comment]
That is an issue I'm aware of, plus I was working on backend of the app (loca + network video sources etc) for v1.0 - Once that's out you should see more of a focus on UI features and fixes.

Off hand, I'm not sure why the video doesn't auto-retry or auto-resume once the connection re-appears, but I'm sure there's some way to fix it as Android devices (phones, etc) all have ways to detect network status changes.

**Comment by theothernt** [comment]
Just a small bit of info. I happened to update my router while the screensaver was running. The video paused like expected. But when the router came back up, nothing happened until the current video was supposed to end, then it faded out and the new video faded in and started playing. No perfect, but good to know it recovers a little bit and won't leave you with a black screen for more than 5 or 6 mins at most.

**Comment by sb76117** [comment]
00:34 CST:
Rebooted router and now I'm staring at a still image of jellyfish...
Waiting...
Router is back up fully...

00:40 CST:
Faded out and new video faded in.

**Comment by theothernt** [comment]
Glad to hear it's doing the same for you. I will improve the reconnection experience in future!
