### ISSUE TITLE
Feature Request: Launch Screensaver on Start

### ISSUE THREAD

**Issue by dimitrij2k** [theothernt/AerialViews#39]
I want to start the Screensaver, when i launch the App (like in the Phoebos Version).

Or is it possible to get a Shortcut Apk that we could place on the Home-Screen and launch the Screensaver manually.

Thank You!!!

**Comment by theothernt** [comment]
So the quickest solution is to find an app that can run a shortcut or just call the 'current screensaver' on launch.

Longer term, I'd like to app to work like Dreamy, which is similar to what you describe - when you start the app, videos play and if you press a button, settings will open and you can change things.

**Comment by dimitrij2k** [comment]
Thats the problem. I just found one app to start the screensaver as a kind of shortcut frim my launcher, but this app doesnt work. Maybe „aerial views“ can offer a shortcut apk or a widget (for wolf launcher/atv launcher) and long term build it in ;-) i love aerial views and hope for the feature. Thx for the fast answer….

**Comment by theothernt** [comment]
Another user of Aerial Views suggested Button Mapper, would that be any good?

**Comment by dimitrij2k** [comment]
Actually i solve the problem with a button remapper, but i want to use the tv remote with hdmi-cec and then the remapper dont work. I think its the cleanest solution with the app itself….

**Comment by theothernt** [comment]
Ok, well having the app startup and go into screensaver mode (as opposed to settings) is on the list but it's probably a few months away - just to let you know.

In the meantime, keep looking for a shortcut or an app that can start an 'Intent' which is what's used to call the screensaver directly. And if you get it working, let me know and I can add the solutions to the documentation!

**Comment by darkj2k** [comment]
This works on my SHIELD.[https://play.google.com/store/apps/details?id=com.brianco.daydreamlauncher](url)
Another one named "Daydream Launcher Icon" also works on my SHIELD.

**Comment by theothernt** [comment]
> Daydream Launcher Icon

Do either of those work properly in Android 11?

If not, I can write one...

**Comment by dimitrij2k** [comment]
I think its just one shell command, i will try at first the Daydream Launcher tomorrow… then we will see 👍🏻

**Comment by dimitrij2k** [comment]
> [This](https://play.google.com/store/apps/details?id=com.brianco.daydreamlauncher) works on my SHIELD.
> Another one named "Daydream Launcher Icon" also works on my SHIELD.

Perfect - Daydream Launcher was exactly what i wanted…. In Wolf Launcher or ATV Launcher i can now set it up perfectly! Launch Aerial Views for Settings and Daydream Launcher for a direct Screensaver accsess. THX

launching the „Aerial Views“ Banner start the Screensaver.
![image](https://user-images.githubusercontent.com/22957404/150102058-892f08c6-0b80-47d2-b637-f6d135749583.jpg)

**Comment by dimitrij2k** [comment]
i switched to an FireTV 4k MAX and "Daydream Launcher" don´t work anymore. Any suggestions for an alternative app?

**Comment by theothernt** [comment]
> i switched to an FireTV 4k MAX and "Daydream Launcher" don´t work anymore. Any suggestions for an alternative app?

My only guess is that the name of the intent/command to start the screensaver is different on the Amazon range of devices, so this app doesn't work anymore. I don't have a FireTV, etc though...

**Comment by theothernt** [comment]
@dimitrij2k if you haven't found a solution yet, it might be work posting on [Reddit](https://www.reddit.com/r/fireTV/) ?

**Comment by dimitrij2k** [comment]
> @dimitrij2k if you haven't found a solution yet, it might be work posting on [Reddit](https://www.reddit.com/r/fireTV/) ?

Yepp, i sell the FireTv and bought a Shield TV (2019) without Pro…

**Comment by theothernt** [comment]
> Yepp, i sell the FireTv and bought a Shield TV (2019) without Pro…

Nice! I hear the Nvidia Shield is a great device - enjoy!
