### ISSUE TITLE
WebM files not detected in SMB Share

### ISSUE THREAD

**Issue by Eagle00Eye** [theothernt/AerialViews#41]
I have managed to connect my network share on my Shield correctly.
It took some setting up. But I got there. I needed to share the specific folder I wanted. Not just the external HDD itself.

The only reason I knew it was successfully when testing the connection was because I threw a random .mp4 into the folder along with my 88 .webm videos I downloaded from YouTube. Totalling 600GB.

It only detected 1 video and testing the screensaver plays the .mp4.

My question. Can you please allow it to detect .Webm extensions please. I assume Exo Player has the functionality to play them just fine?

I will be so grateful if you can manage to implement this as I can't feasibly convert 600GB of .Webm to .mp4. It would take forever.

**Comment by theothernt** [comment]
That's not a problem, it was limited to 3 file extensions as they were the most common. And as I've never used WebM in any way before, ".webm" is the only file extension it uses right?

I should have this in v1.0.1 which will be available on GitHub as a beta in a few days, the Store (and stable version) will follow about 2 weeks later.

**Comment by Eagle00Eye** [comment]
Wow thanks heaps.
.webm and .mp4 are what YouTube mainly uses I think.
I actually got around the issue by renaming all of my files to .mp4 and it is working fine.
I assume Exo Player is smart enough to read the container codec info and not just the file extension.

But if you add further extensions in future releases I am sure it will be of great help to others.

Frame rate matching like "refresh rate" app would be super handy. If it could frame rate match when each video plays. I understand this would be a difficult addition to add. But just throwing it out their as some of my YouTube videos are a weird frame rate and it causes mad judder.

So far though I am loving your app compared to "photo gallery and screensaver"!

Well done.

**Comment by theothernt** [comment]
Yeah, YouTube can output a video in a few different formats depending on the client. If you use something like _youtube-dl_ you can choose between them.

ExoPlayer does indeed use the mime-type and container info to figure out the format, the file extension is just a hint but Unix/Linux systems don't rely on it.

As for frame-rate match, I'm hoping to add it soon so maybe in the next few weeks. Amazon made a library to use with the FireTV so I have to see if it plays nicely with the current version of ExoPlayer.

**Comment by Eagle00Eye** [comment]
Oh wow. That's great news regarding implementing frame-rate matchong. Looking forward to it.

Thanks for making my Shield a great screensaver for my TV.

**Comment by theothernt** [comment]
Btw, I've just read that frame-rate matching is only available for external Android TV devices, no TVs with Android TV built in support it... that is, until Android TV 12.

**Comment by Eagle00Eye** [comment]
Does that mean you won't be implementing it for the Shield and other external devices?

Or you could include a toggle in settings?

**Comment by theothernt** [comment]
I'll definitely be adding it, and you'll have to enable it via _Settings > Performance & Debug_ menu in future.

... it was just in case you try to use it on an Android TV in future or someone else finds this thread 😅

**Comment by Eagle00Eye** [comment]
😂 no problem.
I can't stand Android TV.
Shield with Android 11 is great! 
Can't wait for 12 to be released for 4K UI and auto frame rate matching across the board.
