### ISSUE TITLE
How to launch screensaver with button mapper app?

### ISSUE THREAD

**Issue by DKertson16** [theothernt/AerialViews#43]
I used to use aerial dream for my shield, and had remapped my netflix button on the remote to launch the aerial dream screensaver. Wondering if there is some sort of intent to broadcast or shield command I can run to start the this app in the same way.

**Comment by theothernt** [comment]
It should still work but parts of the app have been renamed, so if you were using an Intent it'll have to be updated.

If you have the old Intent, I can figure out what the new one is?

**Comment by DKertson16** [comment]
Apologies for the picture of the screen but this is what I currently have
![image](https://user-images.githubusercontent.com/44485194/149842014-272f06fa-0f4b-4d1c-b114-bd9911ea04c5.jpg)

**Comment by theothernt** [comment]
No problem at all, screenshots are good! 

The settings you want are...

1. com.neilturner.aerialviews
2. com.neilturner.aerialviews.ui.screensaver.TestActivity

**Comment by darkj2k** [comment]
Start screensaver on SHIELD by Button Mapper:

Broadcase Intent
Package: com.android.systemui
Component: com.android.systemui.Somnambulator
Check "Start as activity"

**Comment by theothernt** [comment]
> Start screensaver on SHIELD by Button Mapper:
> 
> Broadcase Intent Package: com.android.systemui Component: com.android.systemui.Somnambulator Check "Start as activity"

Thanks, I'll probably add these methods to the docs - I think the 3 types are Nvidia Shield, Amazon FireTV and all others
