### ISSUE TITLE
Feature Request: Separate branch for Beta in Play Store + Stable build in Amazon Fire TV store

### ISSUE THREAD

**Issue by yslupdates** [theothernt/AerialViews#45]
Hello, I'd like the option to be able to directly install the beta version of this build in the play store rather than having to sideload the apk please. Also similar idea for at least being able to install the stable build into the amazon fire tv store if possible. I have to use adb commands to change my fire tv stick screensaver to Aerial Views, but it works great! Thanks

**Comment by theothernt** [comment]
That is something I'd like to do in both cases but there are some issues...

**Google Play Store** - it does have a 'beta' feature but I don't think it's available for TVs, I don't see any way to signup for betas, etc but the option is easy to access on the phone (Aerial Views in not a phone app, so it won't appear there btw).

**Amazon Appstore** - I was looking into releasing the app there but I would have to add a feature to allow you to set the screensaver as default, as Amazon removed that screen from Settings. At the moment I'm not 100% sure how to change the screensaver, but I think the app has to send ADB commands locally.

**Comment by yslupdates** [comment]
Hi, thanks for the response!

Just as a reference, I'm in the Jellyfin Android TV beta so it should be possible to do a TV beta!
https://play.google.com/apps/testing/org.jellyfin.androidtv

And understood for the Amazon Appstore limitation. Is it possible to built in an updating feature into the beta app then? Similar to how I can update SmartTubeNext within the app instead of having to sideload each time.

**Comment by theothernt** [comment]
Ahh, I see - that's good to know, thanks. Can I ask, can you switch between the beta and non-beta easily enough? I assume you'd have to visit the same link on your phone/PC/Mac to unsubscribe from the beta?

The auto update feature is something I'm looking into and would be ideal for both GitHub/FireTV users, I think.

**Comment by prabjots07** [comment]
Yes. Same link will also let you leave beta
![982C4FCD-6439-444B-84AB-F546F3494CDB](https://user-images.githubusercontent.com/16275002/152690090-d0e637b4-5811-4843-9ed4-b0dcb1f46606.jpeg)

**Comment by prabjots07** [comment]
This might also help https://support.google.com/googleplay/android-developer/answer/9845334

**Comment by theothernt** [comment]
A small update and some questions...

1) I'm looking at making Aerial Views available in the Amazon App Store, but as there's no screensaver settings app - does this make sense? will a lot of people be confused by this?

2) There is a free app called [Screensaver Settings](https://www.amazon.com/Screensaver-Settings-Loader-shortcut-Fire/dp/B096YPYQRP/ref=sr_1_4?crid=Z8M6WYYQDIK5), does this still work?
