### ISSUE TITLE
Video Player Location Text Just like the Original

### ISSUE THREAD

**Issue by Stackedstudio** [theothernt/AerialViews#46]
When the screensaver starts, the Location text shows up and then fades just like the original Apple TV screensaver.
Also don't forget to add the gradient shadow behind the text.

**Comment by theothernt** [comment]
A feature similar to that plus text customisations are in the works.

**Comment by theothernt** [comment]
An update on this. In the next release you will be able to...

* Add gradients to the top or bottom of the screen
* Configure the overlays (ie. location, clock, etc) to appear initially, then disappear
* Configure any direction or OK button to reveal the overlays when press - with configurable timeout

There is a beta if you want to test the features, or the release should be out in the next week or so.
