### ISSUE TITLE
SMB Import/Export issues in v1.1.1

### ISSUE THREAD

**Issue by darkj2k** [theothernt/AerialViews#50]
Thanks for this great update but looks like they're some issues in  SMB Import/Export.

On my SHIELD Pro 2019 with Android TV 11:

1. Export done as you can see but title need to be changed something like "Done". the file name is:
aerial-views-smb-settings-1645963945658.txt
[https://imgur.com/a/ZbVBCcv](url)

2. Tried to Import to test this function and get this error:
[https://imgur.com/a/1h7kbMO](url)
AerialViews tried to get aerial-views-smb-settings.txt from Download folder but the exported file name is aerial-views-smb-settings-1645963945658.txt so this will never work.

3. So by changing the file name to aerial-views-smb-settings.txt with X-Plore then trying to import again. This time I got "reading file error" as following screenshot. I checked the SMB value and all empty so function is still not ok on SHIELD.
[https://imgur.com/a/PgMXXr5](url)

On my Philips 55OLED806 with Android TV 10.  I copied the renamed aerial-views-smb-settings.txt from SHIELD to the Download folder of my TV. New installed 1.1.1 and test the import function. It quit immediately then I launched it again. The SMB value all import successfully and tested without problem. I tried to import many times but it just quit immediately after click import button.

**Comment by theothernt** [comment]
Thanks for reporting those issues.

1. I'll improve all of those messages to make a bit more sense - and be consistent.
2. I'll remove the random numbers at the end of the settings file.
3. After some quick testing, the import/export feature can crash in a few situations so I'll fix and improve that.

These fixes will be in v1.2 but likely appear in a beta before that, probably in the next week or so.

**Comment by theothernt** [comment]
A small update. I fixed the crash on import. It was a threading issue when updating the UI controls, the last step in the import process after the settings are saved, which is why 'import' works but crashes the app.

**Comment by darkj2k** [comment]
Wow, that was fast. AerialViews is so great on my new OLED TV. Any chance to have slideshow (pictures) folder support as local/SMB video playback?

**Comment by theothernt** [comment]
> Wow, that was fast. AerialViews is so great on my new OLED TV. Any chance to have slideshow (pictures) folder support as local/SMB video playback?

Yes, that should be possible in future but I'm not sure on a timeline just yet.

**Comment by theothernt** [comment]
This bug was fixed in v1.2.
