### ISSUE TITLE
Black Screen on Local Files from USB

### ISSUE THREAD

**Issue by soleurs** [theothernt/AerialViews#51]
On the latest Play Store version (1.1.1) and Android TV 9.0.1 for NVIDIA Shield, I see no video or even a clock when attempting to run from local files stored on the attached USB drive, just a black screen. The files are still the original names when pulled from Apple and are located in a subfolder from the USB's root. Streaming from Apple works fine but would prefer to go another way to save bandwidth.

**Comment by theothernt** [comment]
Can you try uninstalling Aerial Views from the Play Store then re-installing it?

The v1.1.1 update did fix a bug affecting Shield users, a permissions related bug, but the fix doesn't seem to work for everyone but a re-install should. When the app is re-installed, going to Settings > All Videos > Use local videos and enabling it should work.

**Comment by prabjots07** [comment]
I have same issue on v 1.1.1. Videos are in a folder named Aerial in USB stick. Permission is allowed and local videos turned on. Still shows black screen

**Comment by prabjots07** [comment]
Just Side loaded new version and i am not sure what to mention in location. I tried ‘ /storage/2678-32EF/Aerial/’ but shows 0 videos. I got that location from file explorer

**Comment by theothernt** [comment]
@prabjots07 I have a few questions...

1. Are you using a Nvidia Shield as well?
2. Was it upgraded to Android 11? 
3. Is the media scanning feature enabled?

Things to try...

1. Remove Aerial Views completely and install it again.
2. The newly added has a test feature, that should show the number of files seen before and after the filter
3. Only specify a folder name, Aerial in this case, not a full path like /some/place/folder

**Comment by prabjots07** [comment]
1. Yes
2. Yes
3. No and enabling fixed it. Thank you.

**Comment by soleurs** [comment]
I'm still facing this issue, even with reinstalling, testing (the filter even with a custom folder name shows over 1500 video options) and enabling media scanning. It just hangs on "Loading".

**Comment by theothernt** [comment]
Ok, it sounds like another bug, someone else reported something similar so I'll look into it this weekend. Can I ask...

1. In Settings > Any Videos > Test filter settings, how many videos are 'selected for playback' ?
2. Do you know the path or folder name of where your Aerial videos are stored, does it contain spaces? (just trying to rule out a few things)
3. If Local Videos are turned off, I assume Remote Videos work (as a test) ?

**Comment by soleurs** [comment]
1) 1548 (don't ask me why, there's only about 50 in the folder)
2) It's /storage/8E84-5A0A/AerialVideos (the second folder refers to my USB drive)
3) Remote videos do work. But I'd like to save the bandwidth.

**Comment by theothernt** [comment]
Thanks for answering. About the remote videos, I just wanted to make sure that works - I use a network share for my videos.

In Settings > Any Videos > Specify a folder name... do you have 'AerialVideos' ?

Also, if you don't mind, when you test the filter, what are the 3 numbers shown?

**Comment by soleurs** [comment]
1) Yes that’s correct, it’s directed to folders named AerialViews.
2) The three numbers are as follows: Videos Found 8085 | Videos Removed by Filter 6537 | Videos Selected for Playback 1548

I do have plenty of videos on my NAS but the app has network sources turned off. My USB is only used to hold these Aerial videos and my Plex library files. And in the folder AerialViews, there’s only 70 items.

**Comment by prabjots07** [comment]
when you say directed to folder, did you input full path or just folder name?

**Comment by soleurs** [comment]
Just the name, not a full path. I’ve attached screenshots of the settings page and relevant options.

![Aerial Views_20220416_072934](https://user-images.githubusercontent.com/24378229/163649806-557eff7b-5d8c-4bfd-8851-26feafea6ea4.png)
![Aerial Views_20220416_072944](https://user-images.githubusercontent.com/24378229/163649825-9fcdb0f6-7592-422b-b5c7-b4408881f9ed.png)
![Aerial Views_20220416_073132](https://user-images.githubusercontent.com/24378229/163649836-fc95e731-3e77-4256-9f26-b7ec61ce3da9.png)
![Aerial Views_20220416_073142](https://user-images.githubusercontent.com/24378229/163649838-59c547ab-a8ac-4c8e-8d7b-c966c268f133.png)

**Comment by ChaosBlades** [comment]
I have this issue with the network share. I am also getting the Black Screen with "Loading..." forever.
This is a fresh install for the first time with the latest version from Github side loaded.
Streaming the videos from Apple over the internet works without issues.

Share Host is a TrueNAS SCALE server.

Nvidia Shield TV Pro (2019) with whatever the latest OS updates that are available at time of posting.
Network connection between Host and Client is Wired Gigabit.

Network Share Name: AerialViews_HDR_4K
Mount Directory: /mnt/Lora/AerialViews/HDR_4K
Using Credentials
114 Videos Detected
Using videos downloaded from Apple from the link provided on AerialViews Github page. File names have not been changed.
Can view and play videos from a Windows Machine with this share mounted.

I also tried with all the Apple videos in one directory (600+ Videos) with the share named just "AerialViews" with the same result.

Let me know if you need any more information.

**Comment by theothernt** [comment]
> I have this issue with the network share. I am also getting the Black Screen with "Loading..." forever. This is a fresh install for the first time with the latest version from Github side loaded. Streaming the videos from Apple over the internet works without issues.
> 
> Share Host is a TrueNAS SCALE server.
> 
> Nvidia Shield TV Pro (2019) with whatever the latest OS updates that are available at time of posting. Network connection between Host and Client is Wired Gigabit.
> 
> Network Share Name: AerialViews_HDR_4K Mount Directory: /mnt/Lora/AerialViews/HDR_4K Using Credentials 114 Videos Detected Using videos downloaded from Apple from the link provided on AerialViews Github page. File names have not been changed. Can view and play videos from a Windows Machine with this share mounted.
> 
> I also tried with all the Apple videos in one directory (600+ Videos) with the share named just "AerialViews" with the same result.

Thanks for reporting the problem. There is [another GitHub issue on this topic](https://github.com/theothernt/AerialViews/issues/18) (ie. problems playing network videos) which seems like the same problem. I think I have a fix for it so I'm expecting to have that out in the next couple of days.

The issue relates to not formatting username/passwords properly. Although I have a fix for it, if you wanted to confirm it's the same issue then create a very simple username + password such as 'aerial' and 'password1234'.

**Comment by ChaosBlades** [comment]
I can confirm setting a simple username and password resolved the issue. I didn't think I had the same issue as linked because my videos never load even after 30 minutes. My old username had capital letters and my password was very complex.

**Comment by theothernt** [comment]
v1.2.2 has been released which contains fixes for both 1) the SMB issue mentioned and 2) changes how to folder filter works for local or USB storage based videos. 

When either of you get the chance, let me know if it fixes the issues you are seeing?

**Comment by Rickexe** [comment]
No, I just installed Aerial Views and I can't play local files either. I am using a usb connected ssd with my shield tv pro. When I specify the folder called Aerial it's not finding any videos.

**Comment by theothernt** [comment]
> No, I just installed Aerial Views and I can't play local files either. I am using a usb connected ssd with my shield tv pro. When I specify the folder called Aerial it's not finding any videos.

If I can ask a few questions...

1. In Settings > Any videos > Test filter settings, what numbers are listed? (I'm trying to figure out if my filter code is still bad or is this an issue with Nvidia Shields as they handle some things differently to other devices)
2. Do you use any local network features (connecting to network shares) of the Shield?

**Comment by Shawn9347** [comment]
Sorry for the late response. 

1. It says 0 for me. It can't find any videos.
2. No I don't

**Comment by theothernt** [comment]
> Sorry for the late response.
> 
> 1. It says 0 for me. It can't find any videos.
> 2. No I don't

No probs. Can you check that _Storage > Storage > Scan for media automatically_ is enabled?

**Comment by Shawn9347** [comment]
Ok NEVERMIND. It works LOL. Haven't tried it since my last post haven't changed anything and now it's working xD. Have you pushed any updates perhaps?

**Comment by Shawn9347** [comment]
Also do you know if it's possible to start the screensaver manually with just 1 press of a button? I currently have a very complicated sequence my a universal remote that scrolls through the menu and starts the screensaver. Not ideal.

**Comment by theothernt** [comment]
> Ok NEVERMIND. It works LOL. Haven't tried it since my last post haven't changed anything and now it's working xD. Have you pushed any updates perhaps?

No, nothing has changed that would cause it to suddenly work - but the Shield is quirky, so it could have taken some time to index the SSD or even a restart fixed it. Do let know if it happens again!

As for the shortcut, I'll look that one up and get back to you in the next day or so.

**Comment by Shawn9347** [comment]
Okay, Thanks. I did actually downgrade my shield so it's pretty stable. Version 9+ was just a no go for me.
