### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by peat80** [theothernt/AerialViews#52]
**Describe the solution you'd like...**

I would like to know if this project would accept translations.

I could translate the strings of this app into german language. But it would be wasted time if it will not get accepted. So the question is would you merge such a pr?

Thanks for your hard work making this great app. It is a must have for me on android tv. 😍

**Comment by theothernt** [comment]
Yes, I'd be happy to accept translations - it's something that's been on the TODO list for quite a while!

Plus, I haven't got around to updating the README about contributions, etc.

Do you have experience creating the language resources for an Android app or do you need my help to set it up?

Also, as the app is still under development, I might need new translations or updates in the the future if you're able to help.

**Comment by peat80** [comment]
Okay that is cool. I will make a german translation when i have the time and then try to do a pull request when ready. If strings change in the future or new strings will be added i will try to keep german strings up to date in the future. 😀👌

**Comment by theothernt** [comment]
That sounds great - thank you!

And just in case you need it, here is [the official user guide on how to translate text resources in an Android app](https://developer.android.com/studio/write/translations-editor).

**Comment by peat80** [comment]
Please have a look at #53 if this is okay. Have done this with a normal text editor on phone cause i have no android studio.

**Comment by theothernt** [comment]
Give me a day or two to look at it 👍🏻

**Comment by theothernt** [comment]
A friend just had a quick look and suggested a couple of changes - let me know what you think?

After that, we should be good to merge!

**Comment by theothernt** [comment]
v1.2.2 is finally out which includes the German translation. I've added a small credit in the release notes but I do hope to add all contributors to the README at some point!

Also, I did find some hard-coded text strings that are not in the strings.xml ... so I may contact you soon about that 😅

**Comment by peat80** [comment]
Have intalled the update now. 😃👌
There are just are a few bits untranslated.
If you add them to the strings.xml in the future we (or i) will get them translated for sure. 😎

**Comment by theothernt** [comment]
I might ask you to take a look at some of the English -> German strings again in the next week or so as I hope to add all the remaining app text into localisable strings.

**Comment by peat80** [comment]
Sure, sounds good. 😎

**Comment by theothernt** [comment]
Thanks for that update @peat80. I still have more text changes to make but I think I'll just ship the current update (soon) as-is.

**Comment by theothernt** [comment]
Sorry to ask again, but if you have some free time, there are a load of new text strings in the app due to a complete re-organisation of the menus. Big changes to the text should be *very* rare! 😅

**Comment by peat80** [comment]
Sure, i will have a look.
Have already installed the new version yesterday. Great update btw. 😎👌

Should have time to look at the new strings in a few days. 😀

**Comment by peat80** [comment]
Finished updating the strings.

**Comment by theothernt** [comment]
Thanks again for updating the translation - I'm hoping to add the remaining strings into resource files soon-ish.

**Comment by theothernt** [comment]
Quick question for you - do you know what happens when a language is requested (eg. German) but there is no text or resource for that language, does it default to English?

**Comment by theothernt** [comment]
Ah, I think I see it now - it helps to look at the filesystem and not the file list in Android Studio.

/values and /raw are the default so if `openrawresource()` is called and the file for the current locale doesn't exist, I think strings.xml or values.xml is returned and not /values-de/strings.xml

**Comment by theothernt** [comment]
> Where is that file located? 🤔

Here you go...

[comm1_strings.json](https://github.com/theothernt/AerialViews/blob/master/app/src/main/res/raw/comm1_strings.json)

[comm2_strings.json](https://github.com/theothernt/AerialViews/blob/master/app/src/main/res/raw/comm2_strings.json)

Also, the language can be switched in the latest build for testing.

**Comment by peat80** [comment]
Is see. Maybe i can find the time to do this over the weekend. 🤔 😀

**Comment by peat80** [comment]
Translations should be up to date again.
Hope we can see them in a new release soon. 😃

**Comment by theothernt** [comment]
> Translations should be up to date again. Hope we can see them in a new release soon. 😃

Thank you so much! I'm hoping to have that update out in the next week or so.

**Comment by theothernt** [comment]
I've added a few more new strings that need translation when you have some spare time?

**Comment by peat80** [comment]
I'll try to have a look at it soon.

**Comment by theothernt** [comment]
> I'll try to have a look at it soon.

Thank you once again for your help with the translation 🥳

**Comment by theothernt** [comment]
when you have time, there are 10 new videos in the comm2_strings.json that need translation?

**Comment by peat80** [comment]
Added the missing video strings.

Will do app strings after you say they are ready. 😀

**Comment by theothernt** [comment]
> Added the missing video strings.
> 
> Will do app strings after you say they are ready. 😀

Thanks again, I'm hoping to add a lot more text in 1.5.2 🥳

**Comment by theothernt** [comment]
Ok, I've finally added all (I think?) text from the app into resources - and it's ready to be translated when you have time :)

**Comment by peat80** [comment]
Added latest translations.
Did not check if already translated strings were changed.
I have only translated the new english ones.

Also noticed that the string
appearance_date_custom_example
looks wrongly formatted.

**Comment by theothernt** [comment]
> Added latest translations. Did not check if already translated strings were changed. I have only translated the new english ones.
> 
> Also noticed that the string appearance_date_custom_example looks wrongly formatted.

Thanks for the translations.

I removed the "// for example" comment, the text is supposed to be "e.g." though.

**Comment by theothernt** [comment]
Dang, looks like I forgot to include the Capabilities screen strings.

**Comment by peat80** [comment]
Completed (probably)... 🙊🙈🙉

**Comment by theothernt** [comment]
Thanks again - if you notice any strings that I missed, let me know :)

**Comment by theothernt** [comment]
Not translation related, but it looks like there are a couple of bugs in v1.6. I've found the following so far...

* If location is disabled, when you update to v1.6 - the screensaver will crash
* the upper and lower slots are in the wrong order

If you happen to notice anything else, do let me know. I'll probably release an update next week depending on how many crash reports I get (only 1 affected user so far)

**Comment by peat80** [comment]
I've noticed there are a couple of strings in settings / appearance that do use english strings instead of translated ones.
Other than that it seems to work fine here. 😀👌

**Comment by theothernt** [comment]
Ah good, I'll fix those things 😅

**Comment by theothernt** [comment]
> I've noticed there are a couple of strings in settings / appearance that do use english strings instead of translated ones. Other than that it seems to work fine here. 😀👌

Ok, fixed two issues...

1. I forgot to copy some resources into de/array.xml ?! 
2. Translations were not used on the "Date format" dropdown

**Comment by peat80** [comment]
Translations should be ready now for the next update.
😀👌

**Comment by theothernt** [comment]
Ok, that update is live with all the fixes 😅

**Comment by peat80** [comment]
A little too late 4 release it seems... 🤣👌

**Comment by theothernt** [comment]
> A little too late 4 release it seems... 🤣👌

Apologies! I should have messaged you earlier, but at least it's only a couple of items 😅

**Comment by theothernt** [comment]
I've just changed and added some more text. No hurry, I won't be releasing this update for another week or so 😅

Also, I was given access to Lokalise platform for translations. If you'd like to use it, let me know - although if PRs are easier, please stick with that.

And, as always, thank you so much for all the help you've given!

**Comment by peat80** [comment]
Never tried that platform, but that could eventually be more comfortable for tranlations than github. 🧐😀

**Comment by peat80** [comment]
Translations should be updated now.

**Comment by theothernt** [comment]
> Never tried that platform, but that could eventually be more comfortable for tranlations than github. 🧐😀

I just need an email address, then I can send on an invite...

**Comment by peat80** [comment]
peat01@gmx.net

**Comment by theothernt** [comment]
Would you have some time for translation update on Lokalise? No problem at all if you don't have free time!

**Comment by peat80** [comment]
Will try to look at it soon. 😀

**Comment by theothernt** [comment]
> Will try to look at it soon. 😀

Again, thank you so much for your help!

**Comment by peat80** [comment]
1x (fast) komplett neu. 😂😂😂

**Comment by theothernt** [comment]
More text (+ features) are ready to be translated if you have some free time?

**Comment by peat80** [comment]
Had no time yet, will try to look at it soon. 👌

**Comment by theothernt** [comment]
Thank you so much for the updated translation!

Just curious, when using Lokalise - sometimes I rename a key in the code but the text is the same, so it appears as a new translation - does Lokalise suggest the old text meaning you only have to click once to translate that entry?

**Comment by peat80** [comment]
Did not expect that much new text. 😂

It had marked almost all existing strings with a orange dot, altough most of them were not changed. So you have to proof read everything again. But you can mark the old translation as okay. Everything was still there. I hope i have catched all new strings that needed retranslation. Was a lot of text. 😁👌
