### ISSUE TITLE
Incompatible with pipup

### ISSUE THREAD

**Issue by dudududodododedede** [theothernt/AerialViews#54]
Using this on my Nvidia Shield and it is working great

However I am also trying to use this popular android notification API/plugin that is used within many home automation platforms: https://github.com/rogro82/PiPup

Pipup has no issues drawing overtop other apps like youtube, netflix etc, but it is unable to draw overtop Aerial

**Comment by theothernt** [comment]
I'm not familiar with this app so it may take a few days or so to look into it.

Also, video playback in Aerial Views doesn't use anything custom or special so there is a chance I might not be able to fix this, but I will try...

**Comment by theothernt** [comment]
@dudududodododedede can you try using a different screensaver (maybe one of the built-in options?) and see if the window appears on top of those?

**Comment by theothernt** [comment]
I finally got around to testing PipUp with my Google TV + Aerial Views and it works with no problems.

I was thinking maybe a screensaver appears above all content, but that appears not to be the case.

Which Nvidia Shield do you have and what version of Android is it running?

Also, please test again with the *latest* version of Aerial Views from the Play Store. Thanks!
