### ISSUE TITLE
Text on Video is hard to read when video is mostly white

### ISSUE THREAD

**Issue by ChaosBlades** [theothernt/AerialViews#55]
When the video is mostly white like on snowy areas the white text of the time and location is very hard to read.

Fixes for this would be to increase the drop shadow or darken the corner of the screen were the text is present.

**Comment by theothernt** [comment]
Yeah, a feature like that has been requested by a few people - the same with text sizing, etc.

I think the most flexible solution is to give people a number of options when it comes to shadow, text size, etc. I'll probably start planning it soon :)

**Comment by nomadism19** [comment]
Just to add, as someone with Apple TV 4K, the exact same text settings including font/size/border would be best. I have been hoping for this for many months, thanks.

**Comment by theothernt** [comment]
@nomadism19 are you able to take screenshots by chance, as I don't have access to an Apple TV at the moment?

Either way, the next few updates will be able the UI and settings.

**Comment by theothernt** [comment]
A small update on this. The next version, due in a day or two, will improve the legibility of the text in those newer Apple videos which feature a lot of snow. 

Hopefully in the update after that, I'll allow you to change the text properties yourself - just be aware that it's very difficult to pick text colours, etc that will look good in all current Apple videos.
