### ISSUE TITLE
Network Videos do not load

### ISSUE THREAD

**Issue by BatJoe** [theothernt/AerialViews#56]
Using the latest version on the nVidia Shield TV Pro. 

Trying to load the apple videos I downloaded to my Synology NAS with SMB. Put in the server connection info. Tested the connection, it says it found 113 videos. When I try to run the screensaver nothing happens. Loading at the bottom left appears and then it seems to crash and goes back to the Shield Dashboard.

**Comment by theothernt** [comment]
Thanks for reporting the issue. There were a couple of issues with SMB playback reported in the last few weeks, so can I just rule out a few things first...

1. Do remote videos play ok? (ie. disable local and network videos, enable Apple videos)
2. Are you using v1.2.2? this is the version on GitHub but it's not out on Google Play yet (should be in the next few hours)
3. Does your password use any special characters? (*&%#@ etc)

**Comment by BatJoe** [comment]
> Thanks for reporting the issue. There were a couple of issues with SMB playback reported in the last few weeks, so can I just rule out a few things first...
> 
> 1. Do remote videos play ok? (ie. disable local and network videos, enable Apple videos)
> 2. Are you using v1.2.2? this is the version on GitHub but it's not out on Google Play yet (should be in the next few hours)
> 3. Does your password use any special characters? (*&%#@ etc)

Remote videos play fine, as do USB.

I am using whatever version is available on the Google Play store via the Android Shield TV Pro.

My password does use #

**Comment by theothernt** [comment]
> My password does use #

Well good news - the update going live will fix the issue. It should be today, I'm just waiting on Google Play to approve it.

I'll report back when it's live so you can update and try again...

**Comment by BatJoe** [comment]
Great. Thanks for the quick response.

There is another thing I have noticed: when you increase the playback speed setting for the media it seems to add more stutter to the video, the higher you go.

Is it possible to also have simply a timer setting for how long we want the current video to play for? As I suspect increasing the playback speed is what is causing the stutter as it seems fine at default speed.

One of the main reasons I like your app is the OLED burn in settings, so I like the options to be able to move the clock around and adjusting how often each video is playing. Since the clock remains static in the same spot on the current video, being able to have a solution to switch to another video is useful.

Also, sometimes I find the clock hard to see depending on the video, perhaps there could be some kind of setting to help make the font more clear, either bolding, drop shadow for text, etc?

That's a lot I know. Thanks for your efforts.

**Comment by theothernt** [comment]
That update should be live on Google Play now, let me know if it fixes the issue. I will reply to your questions later on today...

**Comment by theothernt** [comment]
> There is another thing I have noticed: when you increase the playback speed setting for the media it seems to add more stutter to the video, the higher you go.

I'll look into this but I'm not sure there's too much I can do as feature is provided as-in by the video player. Typically hi-speed playback of audio (eg. podcasts) or video (eg. YouTube 1.5x) requires processing before hand and I don't think ExoPlayer (what I use) does any of that. Have you tried it with a local video?
 
> Is it possible to also have simply a timer setting for how long we want the current video to play for? As I suspect increasing the playback speed is what is causing the stutter as it seems fine at default speed.

Do you mean you'd like to change videos after a fixed time (eg. 30 seconds) as opposed to the actual length of the video? if the playback speed is set to 2x, for example, a 3 minute video will play in 1min 30 seconds.

> One of the main reasons I like your app is the OLED burn in settings, so I like the options to be able to move the clock around and adjusting how often each video is playing. Since the clock remains static in the same spot on the current video, being able to have a solution to switch to another video is useful.

If you've enabled the **Alternate text position** option, the clock and location will change position from left to right which is enough to avoid burn-in, from what I've read. You only have to worry about burn-in if you have a much older OLED TV and static elements remain on screen for hours at a time.

> Also, sometimes I find the clock hard to see depending on the video, perhaps there could be some kind of setting to help make the font more clear, either bolding, drop shadow for text, etc?

A few people have mentioned that so I'll address it in the next month or so.

> That's a lot I know. Thanks for your efforts.

Thanks for the feedback and reporting the issue!
