### ISSUE TITLE
Version 1.3 crashes while trying to open app

### ISSUE THREAD

**Issue by peat80** [theothernt/AerialViews#62]
**What were you trying to do...**
Installed latest version on shield and tried to open the app. 
**And what actually happened (ie. describe the bug)...**
It does not open. Just crash / close. 
**What kind of device do you have? (eg. Nvidia Shield, Sony TV, etc)...**
Nvidia Shield TV Pro

**Comment by peat80** [comment]
Tested on my Bravia A90J now. Same behaviour there. Also crashes there.

**Comment by theothernt** [comment]
Hmm... this doesn't sound good. And are both devices set to German language?

**Comment by peat80** [comment]
Sure they are. Tried changing tv to english but that doesn't help. 🤔 Screensaver also does not work. Unistalling and reinstalling 1.2.2 and everything works again. 🤷🏻‍♂️

**Comment by theothernt** [comment]
Damn. Same on my device when I installed the update via ADB. I might be an issue with the APK.

I should have an update in 10 or 15 mins.

**Comment by theothernt** [comment]
Ok, the fix is up... I made a small change and mistake to logging which caused the crash.

Can you download v1.3.0 again (it's a new APK) and see if it works for you?

**Comment by peat80** [comment]
Damn, that was a fast fix. Updated apk runs fine. Thx again. 😀 So this issue can be closed. 😃

**Comment by theothernt** [comment]
Thanks for reporting it. I do run the latest releases on my devices but I use build + install process, and don't install the APK itself. I'd better start as this kind of issue has happened twice 😬
