### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by marcopar** [theothernt/AerialViews#63]
Just a placeholder to say I'm working on it.

**Comment by theothernt** [comment]
Ok, most of that should be done but there are other strings I'll add to the res. XML files over the next few days.

**Comment by theothernt** [comment]
Would it help if I added an auto-translated version of all the english strings to start with?

**Comment by marcopar** [comment]
Nah, it would help if I got serious about finishing the translation.
Sorry, I forgot about this, I'll try to get on it again.

**Comment by theothernt** [comment]
v1.7.1 is out, thanks again for your translation work!
