### ISSUE TITLE
Can't open screensaver settings on Google TV 

### ISSUE THREAD

**Issue by theothernt** [theothernt/AerialViews#65]
**What were you trying to do...**
Open the system settings to change the screensaver timeout

**And what actually happened (ie. describe the bug)...**
Nothing happens when I select the menu option. The system settings screen does not appear. This stopped working after the recent update to the Google TV.

**What kind of device do you have? (eg. Nvidia Shield, Sony TV, etc)...**
Chromecast/Google TV

**Comment by theothernt** [comment]
I've reset my Google TV, re-installed Aerial Views and I still can't access the screensaver settings screen.

So it's either been removed or it's a bug.

**Comment by darkj2k** [comment]
Looks like the activity of "device.display.daydream.DaydreamActivity" was remove from "com.android.tv.settings" after latest update of Google TV.

Pls add an start AerialViews screen saver activity to AerialViews so we can start the AerialViews screen saver by mapping it to tvQuickActions or Button Mapper.

**Comment by theothernt** [comment]
> Pls add an start AerialViews screen saver activity to AerialViews so we can start the AerialViews screen saver by mapping it to tvQuickActions or Button Mapper.

What was the previous command/Intent that worked for you?

**Comment by theothernt** [comment]
@darkj2k  I made the TestActivity available in the latest update - v1.3.1. 

I tested it with the following command `adb shell am start -n com.neilturner.aerialviews/com.neilturner.aerialviews.ui.screensaver.TestActivity`
