### ISSUE TITLE
Enhancements to playback speed feature

### ISSUE THREAD

**Issue by theothernt** [theothernt/AerialViews#67]
A number of additions have already been submitted by @marcopar but I'm recommending a few changes...

1. Notification when speed is changed?
2. The left/right key press ability should be off by default
3. User can only change playback speed every 2 seconds or so - change from the play isn't instant, can cause exceptions
4. User cannot change speed of a video 3 seconds before it ends
5. Check video state before playback speed change (isPlaying event state?)

I'm happy to make the above changes, but either way, let me know what you think @marcopar 😅

**Comment by marcopar** [comment]
Yes, ok for me.
And thanks for making the changes,I don't have much spare time and energy lately.

**Comment by theothernt** [comment]
I've disabled changing playback speed during playback temporarily as I want to get v1.3.1 out to fix a few small issues.

All the changes above should be in the next release 😅

**Comment by theothernt** [comment]
Ok, all of changes have been made and are merged into the master branch if you'd like to try it sometime?

**Comment by marcopar** [comment]
Ok, I will install it on my shield in the weekend.

**Comment by theothernt** [comment]
Great, no hurry (as usual).

The speed changing seems to work fine (your code), and I've added those delays + notifications.

I've only done a little testing - most around skipping a video + trying to change the speed as often as possible - so far, no crashes. I'm happy enough with the little notification.

**Comment by marcopar** [comment]
So far it's working ok.

I would reduce the change speed deadzone to 2 secs.

**Comment by theothernt** [comment]
Ok, change delay set to 2 seconds :)

**Comment by theothernt** [comment]
That feature is finally live 🥳

**Comment by marcopar** [comment]
Great.
I noticed some stuttering at certain speeds. I believe it's normal since we
change the speed with a percentage.
Do you know if it's possible to get the clips FPS and then set the speed in
a somewhat more "base FPS" friendly way....like if it's 24 use multiple of
6 or 8...surely not 5...things like this?

**Comment by theothernt** [comment]
Just made some changes to the playback speed list... it's now 0.2 ... 0.8 ... 1.4 ... 2.

I've also removed any speed after 2x as I'm not sure why anyone would use it :)

Another user has confirmed that if a 30fps video is played at 0.8x on 24hz... it's smooth - unlike at 1x where its jerky

**Comment by marcopar** [comment]
But that would work only for 24fps videos isn't it?
With custom sources and local sources it's entirely possible we have 50 or 60 fps videos.

Ideally we should check the video fps and set multipliers accordingly.
Last time i checked i wasn't able to find that information but i don't know that API very well.

**Comment by theothernt** [comment]
> But that would work only for 24fps videos isn't it? With custom sources and local sources it's entirely possible we have 50 or 60 fps videos.

I don't know in that case - I can only speak to a 30fps video played on a 24hz screen. 

> Ideally we should check the video fps and set multipliers accordingly. Last time i checked i wasn't able to find that information but i don't know that API very well.

It appears that if the numbers divide nicely, then the player will do it's best to fit the video inside the 'hz' window. 

Also, I have no idea how the internals of ExoPlayer work 😅

**Comment by theothernt** [comment]
That latest update does change the speed intervals, let me know if you have any issues (I'm seeing a crash from 2 people at the moment)
