### ISSUE TITLE
ExoPlayer NullPointerException when playing remote videos

### ISSUE THREAD

**Issue by DavidMaza** [theothernt/AerialViews#68]
Hello,

I'm trying to play remote videos on a CCGTV from an SMB share.

I can enter the hostname, path and credentials successfully in AerialViews. When I click on "Test connection settings", it says that it could successfully connect to the SMB share and found 1 video.

However, when I click "Test screensaver settings", a toast message appears saying "Error while trying to play...".

Streaming Apple TV videos from the Apple servers works okay. I just can't get the remote videos to work from an SMB share.

I tried opening the video on a PC using the same SMB guest credentials. The video loaded fine.

Below is an excerpt from Logcat with an ExoPlayer NullPointerException in it.

[Logcat.txt](https://github.com/theothernt/AerialViews/files/9332565/Logcat.txt)

**Comment by theothernt** [comment]
If I can get a bit more info...

1. What kind of NAS or server are you using for the SMB share?
2. Can you try going to Settings > Performance & Debug > Select SMB dialects and make sure any of the v3.x are not selected

Also, and this isn't part of the issue, but did you rename the Apple videos are you downloaded them?

**Comment by DavidMaza** [comment]
1. It's a Synology DS418
2. I initially tried selecting SMB 2 in the troubleshooting menu and unticking the boxes for SMB 3 and vice versa but didn't have much luck. I got the same error.

I downloaded the videos a few years ago using an Apple Aerial video downloader tool.

I tried downloading them from https://aerial-videos.netlify.app/ instead and using those videos but got the same error.

**Comment by DavidMaza** [comment]
Yes, you're right! Using a proper username and password instead of just "guest" worked perfectly.

The "guest" credentials work okay in other applications and in Windows, but I guess maybe things are a bit different here.

Thank you.

**Comment by theothernt** [comment]
Yeah, I was just testing the app and 'guest' access in Aerial Views is broken. Anonymous or username + password will work though.

I should have it fixed in the next day or two, but the next update is probably a week or two away.

**Comment by DavidMaza** [comment]
🥳🥳 Thank you!!! 😀

This app is very cool. It's by far the coolest app I've seen so far on Google TV. Thanks for your great work!
