### ISSUE TITLE
Black Screen After First Video

### ISSUE THREAD

**Issue by jordanwalkert** [theothernt/AerialViews#72]
I am using this screensaver on a Zidoo Z1000 Pro Media Player. I installed the APK via the Android settings and almost everything functions perfectly. However, I am only getting the first video of the screensaver to work properly. When it goes to the next video, or if I press left or right on the remote, the original video fades out and then it remains on a black screen. It does this regardless of SDR or HDR.

I have a new LG C2 OLED TV that supports both HDR and Dolby Vision. If I select the Dolby Vision setting, I actually do get proper Dolby Vision at first but again- it only works on that first video. I have not figured out how to use local video files from a USB yet so this is just with the Apple streaming videos. Happy to supply any additional information, thanks!

**Comment by theothernt** [comment]
Thanks for reporting the issue.

1. Can you try the H.264 option as well (I'm guessing it'll have the same issue but it's worth a try)
2. In _Settings > Debug & Performance > Capabilities_, what codecs are listed?

Next, it might be worth trying other video apps or player to see if they have the same issue. 

Af that, it might be necessary to get debug logs from the device which involves enabling Developer Mode, downloading some developer tools to a Mac or PC, then saving the logs and posting them here.

**Comment by jordanwalkert** [comment]
So it turns out that any 1080p option, including H.264 and Dolby Vision work perfect. It’s the 4K options that only display the first video and go black upon changing to the next video. This is odd because my device does in fact support all resolutions up to 4K and I have the display options set to 4K for the main interface.

I am noticing that the capabilities shows the maximum resolution for the UI is 1920x1080 which is also odd since as I mentioned, the entire device and menus all output 4K. I will leave it as 1080p for now so it continues to function, however it’s a shame that the higher resolution can’t be taken advantage here. Especially since the device should be able to support it. Any chance an update in the future could enable this?

**Comment by jordanwalkert** [comment]
![25D57FE2-3505-4F30-A6CC-49015F18B6B6](https://user-images.githubusercontent.com/113207199/189498300-ad814e71-37c3-4921-bcd9-638ed81ccb0c.jpeg)

![5B569764-5DD2-4B49-8110-B56F4825DF64](https://user-images.githubusercontent.com/113207199/189498304-6fec3706-d910-4617-a305-3836c9f4dad7.jpeg)

Hopefully these images show up. These are the codecs that are listed.

**Comment by theothernt** [comment]
Thanks, the extra info helps a bit. And just so I understand...

1. When you select any kind of 1080p video it plays?
2. When you select any kind of 4K video it does not play?

**Comment by jordanwalkert** [comment]
That is correct. All 1080p modes perform as intended. Both 4K modes start normally and play first video as they should, but when it cycles to the next video or pressing left/right to manually cycle it, it fades to black and never comes back on.

**Comment by theothernt** [comment]
The fact it'll play one 4K video then stop is really, really strange. I don't even have a good guess at what could be causing that - as my app just makes a video playlist, then plays one video after another.

Getting logs (ie. text files showing all the info and error messages) from the device might be the only way to figure out what's going on as it sounds very non-standard to me.

**Comment by JustMaris** [comment]
I have the same issue.
Using 4k only plays one video and then shows a black screen.

Switched to 1080p, and videos keep playing continuously, and I can even swipe to the next video without issue.

It almost feels as if there is some issue downloading the media.

I am ready to help by providing logs from 4k. I just need to understand how to get the logs.

**Comment by theothernt** [comment]
What device do you have? also, turn on 'Media toast errors' in Settings > Advanced.

**Comment by JustMaris** [comment]
I have TCL 50P7K.

**Comment by JustMaris** [comment]
This is the error that pops up:

MediaCodecVideoRenderer error, Index=0, format=Format(1, null, video/mp4, video/dolby-vision, dvhe.05.07, 25255458.

**Comment by theothernt** [comment]
It looks like an issue with Dolby Vision playback. I'd recommend you change the video quality to 4K SDR and try again?

**Comment by JustMaris** [comment]
I wonder why 1080p Dolby Vision works and watching 4k Dolby Vision in Disney+ works as well.
But I will try that change.

**Comment by theothernt** [comment]
It's very hard to explain these issues when they are so rare as Dolby Vision works fine on nearly all TVs that support it. I can only guess it's a bug with current firmware on the TCL model.

I've had no playback issues like this reported for a long time.

**Comment by JustMaris** [comment]
Tried 4k without Dolby Vision.
A similar error still:

MediaCodecVideoRenderer error, index=0, format=Format(1,
null, video/mp4, video/hevc, hvc1.2.4.H150.B0, 8164641, ...

Seems to be 4K related, not dolby vision.

**Comment by theothernt** [comment]
Hmm... that is very odd!

Can you turn off the Apple videos and only try the Jetson videos in 4K?

All the videos are in different formats, so it's possible that some will play in 4K while others will not. 

Also, if you have time - you could also try the "Allow fallback decoders" and set "Enable tunneling" to off.

**Comment by JustMaris** [comment]
I tried Jetson and Robin media sources in 4k, both with and without fallback decoders. Didn't work after the initial video.

Tunelling was already turned off, because I initially assumed that it could be causing issues.

One thing to note is that in the device capabilities, it says UI resolution 1080p, Max. video resoluton 4k.

Could it be related to the UI resolution not being 4k, due to which any 4k playback is failing after the initial video.

**Comment by theothernt** [comment]
The 1080p UI and 4K video resolution is normal - it's a limitation of 99% of Android/Google TV devices.

**Comment by JustMaris** [comment]
Understood. Thank you for explaining.
