### ISSUE TITLE
Tries to start but crashes

### ISSUE THREAD

**Issue by manc01** [theothernt/AerialViews#76]
I noticed that Aerial Views was not working on my Nvidia Shield TV Pro 2019 so I looked at the app settings. I haven't changed anything but if I try to test the screensaver settings the app closes and returns to the home screen. It was perfect recently.

**Comment by theothernt** [comment]
Thanks for reporting the issue. Is the app installed from the Play Store or sideloaded?

**Comment by manc01** [comment]
I think that it was from the play store but I am not 100% sure.

**Comment by theothernt** [comment]
Ok, also can I double check what video sources you use (remote apple, local/usb vids and/or local network vids) ?

**Comment by theothernt** [comment]
Just trying to narrow things down...

1. Can you turn off the Local Videos option and just use remote videos _only_ - does that work ok?

**Comment by manc01** [comment]
Hi again,

When I turn off local videos it looks like it is going to play back a video file, I get a black screen and a number on the screen “2131755164”. I hope that I can fix this, I love this app!

Cheers Paul

**Comment by theothernt** [comment]
The numbers you are seeing are a different bug, which will be fixed soon.

As you have turned off _Settings > Any Videos > Use Local Videos_, there are no videos. Can you enable _Settings > Apple TV Videos > Use Apple videos_ and see if that works?

(the issue you are seeing with local videos stores on a USB device can be fixed, don't worry!)

**Comment by manc01** [comment]
Hi there,

Yes Apple videos are working. Where are you located, just out of interest? I am in Australia (Adelaide)

Cheers Paul

**Comment by theothernt** [comment]
Thanks, that confirms the basics are working.

I'm based in Dublin, Ireland which is GMT or 9 hours behind you.

If you want to, I have a beta version of the app you can try which has a fix. You will have to side load the APK though - is that ok?

**Comment by manc01** [comment]
Hey I live for betas! Send it through. Dublin is a brilliant city, I have
great memories of it.

Should I uninstall the version that I have first or just install over the
top? I'm off to sleep in a minute. I will report back to you.

Cheers Paul

**Comment by theothernt** [comment]
On the beta front, I'm attached a version from Dropbox (which I'll remove later)

[Aerial Views 1.3.2 Beta 1](https://www.dropbox.com/s/5zowumy2jqk3og8/aerial-views-1.3.2-beta1.apk?dl=0)

If there are any issues installing this, then remove the older version and try again. Also, remember to disable the 'remote Apple videos' and make sure the 'Use local videos' option is enabled.

It is possible this version won't fix the issue. If not, I'll try one more fix which should. Thanks for your help and patience with this issue so far!

**Comment by manc01** [comment]
Hi Neil,

The app did not crash but it still is not playing back files. Lets keep trying, I am sure that we will get there.

Cheers


Paul

**Comment by theothernt** [comment]
Thanks for testing that build. If you wouldn't mind, can you try v1.3...

https://github.com/theothernt/AerialViews/releases/tag/1.3

(I think v1.3.1 has the bug, this should prove that)

**Comment by manc01** [comment]
Hi Neil,

The app is still crashing on the latest version. I am trying to playback from a USB using the folder filter. 

Cheers Paul

**Comment by theothernt** [comment]
Just to double check, did you install v1.3 and not v1.3.1 ?

**Comment by theothernt** [comment]
Any update, I do have a new beta to try at all ?

**Comment by theothernt** [comment]
Yes, here is a new beta to test...

[Aerial Views v1.3.2 Beta 2](https://www.dropbox.com/s/lh5reizski4z68n/aerial-views-1.3.2-beta2.apk?dl=0)

**Comment by theothernt** [comment]
Ah, there was a bug but it's fixed now. Can you download the APK from the same link above - it should work now?

**Comment by manc01** [comment]
Hi again,

It is working!!! Thank you so much. If there is anywhere that I can leave a positive review, can you please let me know?

Cheers Paul

**Comment by theothernt** [comment]
Fantastic!!

The bug you found related to how file names are handled. It took a few attempts but now it's fixed 🥳

I'll be submitting the app update to Google in the next week or so, so please continue to use that v1.3.2 Beta 2 for the moment.

If you'd like to leave a review after the update is live, I think it's only possible to do so via [the Play Store website link](https://play.google.com/store/apps/details?id=com.neilturner.aerialviews).

**Comment by theothernt** [comment]
v1.3.2 should be live in the Play Store in the next few hours 🥳

**Comment by manc01** [comment]
Yes, I did. I noticed that it did not say beta

**Comment by manc01** [comment]
Hi again,

If you have any new builds please let me know.

Cheers Paul

**Comment by theothernt** [comment]
There aren't usually betas unless there's a specific fix I need to test with a small number of users.

The latest version from the Play Store should work for you?
