### ISSUE TITLE
Using the app on a Hisense 50U6G

### ISSUE THREAD

**Issue by schroef** [theothernt/AerialViews#77]
Im using Aerial on OSX and was looking around for windows version when i bumped into this Android version. I was wondering how the videos are cached? If so does it then deleted vidoes to make space for the new once?

Ive already have many of the video so i can use local playback. Not sure it will run from an USB though my Hisense has about 3gb of free storage i believe.

**Comment by theothernt** [comment]
Compared to the macOS version, Aerial Views is quite simple and lacks most of its features. It can either stream the videos directly from Apple or you can download the videos *yourself* and play them locally via USB storage or a NAS - internal storage on nearly all Android TV is tiny so there's no automatic stream + download option.

If the videos are downloaded and *not* renamed, Aerial Views will show the locations, points of interest, etc.

**Comment by schroef** [comment]
So what happens when it plays and has no storage?

**Comment by theothernt** [comment]
By default, the videos will be streamed (and not stored) one by one.

If you download the videos on put them on a USB key, you would disable the remote Apple videos and only use 'Local videos'.

**Comment by schroef** [comment]
Thanks, yes that is the plan. Ive got about 100 videos on a USB stick, hope its works on my Hisense 50U6G. Otherwise i need to fumble a bit with that ADB i read.

**Comment by schroef** [comment]
Thanks! I got about 100 videos and will use a USB stick, hope it works on my Hisense 50U6G. Otherwise i can always check that ADB i believe.

**Comment by theothernt** [comment]
You should be ok - most Android TV devices allow you to set a 3rd party screensaver.

But if you do run into problems, I'll be happy to help out.

**Comment by schroef** [comment]
It worked straight out of the Box :) Though i needed to reformat my usb from ExFat to FAT32. TV would not recognize it. It looks amazing :)

Also noticed the cache stays very low, after couple minutes i checked the cleaning app, there was just about 56mb.
I have Goovee lightbars with a camera system and makes it look extra nice :)
![AerialViews-HisenseU6G](https://user-images.githubusercontent.com/6923008/191384589-a6da585b-9ec3-4457-aee9-e7acb6dcd27a.jpg)

**Comment by theothernt** [comment]
And if your TV or device has no way to change the time out, you'll have to use an ADB command to change it.

As you have a Mac, you'll have to download the SDK tools (mentioned in the README of this project) then run the following command...

`adb shell settings put system screen_off_timeout NUMBER`

where `NUMBER` is the amount of time in milliseconds. 1 minute is 60000, 5 minutes is 300000, etc.

**Comment by schroef** [comment]
> That's a really nice setup!
> 
> Although the app itself doesn't grow or store data in the cache, it uses Firebase (Google) for basic analytics and crash reporting - that uses a few MBs ove time.

So the video are buffered and that is removed right after, im just curious how it works

**Comment by theothernt** [comment]
> So the video are buffered and that is removed right after, im just curious how it works

No, typically 'buffered' in terms of video means part of the clip is pre-loaded into memory (or RAM). So while a video is playing, the player loads the next 10+ seconds into memory, not storage. If you close the app, the memory is freed up (this is the same on all platforms - iOS, Android, Windows, etc).

When Android refers to the 'cache' it's talking about files or data that is saved to local storage or USB which persist until cleared automatically, at a certain date or by the user manually.

**Comment by theothernt** [comment]
> My TV has a time-out seting, its starts at 5 minutes and goes up to 1 hour i blieve.

Typically Android TV devices have a 1) screensaver timeout and 2) standby timeout ie. when to turn off the TV after no input from the remote control.
 
> PS there is one thing i noticed. While i was playing PS4 and was in the pauze menu for a while. The screensaver kicked in, thats kinda weird. I also would not stop when i pressed menu button again, it would stop show the game for couple milliseconds and start the screensaver again. I had to press the TV remote to exit the screen-saver.

If your TV is using an external input (PS4 via HDMI, etc), the screensaver should not run. I have games consoles and this has never happened. Also, it's the Android OS that decides this, not my app. It does sound like a bug or issue with your TV.
