### ISSUE TITLE
WebDAV support

### ISSUE THREAD

**Issue by TtuxX** [theothernt/AerialViews#78]
**Describe the solution you'd like...**

Hi there @theothernt ! :)

Thank you so much for your great app and for adding the option for external media, this is really awesome :)

I would love to have Webdav support on your app, as I am using Nextcloud, and accessing Webdav is much easier for me (and maybe provider-agnostic) than SMB.

Thank you very much in advance for your kind help.

Best regards

**Comment by theothernt** [comment]
That's a good idea!

I did look into using a Webdav library for Android, but it's not actively maintained, so it might take a while to get it working.

Plus, I'm going to be away for the next 2 or 3 months so development will be quite slow!

**Comment by TtuxX** [comment]
Ah... thank you very much for your help and the transparency of this information !
I look forward to this feature but will patiently wait until you will have time to work on it :)

Thank you so much !

**Comment by theothernt** [comment]
Small update. It appears there is finally a library I can use - it's for Android and is actively developed.

I'll give you an update when I have something working.

**Comment by theothernt** [comment]
When entering the details for a WebDav connection, is it common to ask for a complete URL 

eg. https://192.168.1.2:5003/videos/aerial 

or do some apps ask for all the details separately...

HTTP/HTTPS
IP/Hostname
Port
Path

I'm trying to figure out what would be easier (and less error prone) to enter on a TV with a d-pad.

**Comment by theothernt** [comment]
I'm going to go with my 2nd option - have a serious of inputs as I think it's less likely that people will make mistakes that way.

I might have a beta for you tomorrow (Sat, 29th)

**Comment by theothernt** [comment]
Ok, here is [Aerial Views v.1.7.2 beta 1](https://www.dropbox.com/scl/fi/g04a8xt0taplxlxswokcv/aerial-views-1.7.2-beta1.apk?rlkey=zimbflmu6z48rwqotnsvd6n45&dl=0).

WebDAV support should work but it's only had minimal testing, so let me know if you find any issues. Also, both photos and videos are supported.

**Comment by theothernt** [comment]
> It also works kinda for videos, but I cannot have more than like 5-7 seconds of loading, then it freeze and skips to the next video (server is on LAN with ethernet so bandwidth should not be the issue, and media actually play well for few seconds).

Ok, I'll look into this. Roughly, what is the file size and length of some of the videos?

> Have an option to make the folder search recursive and include all the following content? With like a pop-up displaying live the folders names that are being crawled during content indexing (that would be displayed from the connection test and until the end pop-up that summarise the media scan results)

When I have playback working reliably, I will add a recursive option. But I'm not sure I can add any kind of progress to the file scanning. Unless you have 20k files, it should be able to get a file list in a few seconds. 

> Be able to browse host folders and select them with the remote instead of manually inputing the path? It would be so handy to select one (or even ideally multiple) folder(s) just with the TV stick! When digging deep in a path, having to type it becomes increasingly difficult

If I find another project that provides this, I will use it - but in the meantime, it's a bit too much work for me. My only advice to entering paths, and I have to do it a bit because of testing, is to use the phone app which makes text entry a bit faster.

**Comment by theothernt** [comment]
If you have some time, can you try the Nova Video Player - it uses a version of the library I'm using. I want to see if it plays video without issues.

Their fork/version of the library has some fixes, so I may use that.

**Comment by theothernt** [comment]
Here is [an update build](https://www.dropbox.com/scl/fi/3mtb1u0q09bdshf6k4rdn/aerial-views-1.7.2-beta1.apk?rlkey=zzfxpb6mg1trldnv6vzpg7onu&dl=0).

I've updated the internal WebDAV library and added subfolder support.

**Comment by theothernt** [comment]
Ok, here is [another build](https://www.dropbox.com/scl/fi/h6xug08spwsnmffoubtj3/aerial-views-1.7.2-beta1.apk?rlkey=904531yo4vmkd293e2d23wkgw&dl=0) with a different version of the library. It's the same version that Nova Video Player uses.

If the issues continue, I'll have to make a debug build for you. You'll then have to use the ADB tools to collect the logs and send them to me.

Also, what device are you using?

**Comment by theothernt** [comment]
Here is[ an updated build](https://www.dropbox.com/scl/fi/gcnz1gal8z83wzccbgc9p/aerial-views-1.7.2-beta1.apk?rlkey=5yh4vbsm674nrcwfh0fyitn1h&dl=0). I've fixed the path handling so lets test that first.

Also, looking at the log above, your hostname + IP and path name should be set to...
* 192.168.1.1:80
* /remote.php/dav/files/user

**Comment by theothernt** [comment]
v1.7.2 is now out, if you're running a beta - please update! thanks.

**Comment by theothernt** [comment]
A small update. I was able to replicate the loading delay when using WebDav. I'm not sure why it wasn't obvious before, but it was a simple fix.

It will be Aerial Views v1.7.6 due in a couple of weeks, or the public beta (1.7.6 beta2 due in a few days).

**Comment by theothernt** [comment]
Sorry it took so long!

Basically, most videos just play from the start of the file - no issue there. But with some videos, the player needs to read from the start + end of the video. The problem is, my code didn't support seeking, so it would download the whole video just to read the end of it, hence the long delays.

Anyway, the fix has been tested a bit and seems to work well.

**Comment by theothernt** [comment]
Ok, the beta is live, you can sign up... https://play.google.com/apps/testing/com.neilturner.aerialviews

Or wait a week or two for the stable release.

**Comment by theothernt** [comment]
Ok, I can make a new beta build if you like? v1.7.6 is feature complete, I'm just making a few small tweaks before release - so it's ready to use. Plus you can run the beta, then switch to v1.7.6 when it's released with no issue.

Also, thank you so much for your kind words and the tip 🎉
