### ISSUE TITLE
Local file playback support

### ISSUE THREAD

**Issue by CodenameFalcon** [theothernt/AerialViews#79]
First of all I want to say this screensaver is pretty good as it is right now.
I have set it up on my Nvidia Shield with both Apple and local video playback.
I would like to ask about the limitations of the local video playback feature.
I have over 50 UHD files locally configured, some without HDR, some with Dolby Vision and some with HDR10.
The screensaver only "accepts" about 30 of the video files available. I cannot find any way to tell what files are supported and what are not, nor any reasoning behind it in your documentation.
Can you please advise why not all the files would be supported? Perhaps update this app to advise which files are not supported?

**Comment by theothernt** [comment]
I have a few questions to narrow things down...

1. Are all the videos from 1 source (eg. Apple) or multiple?
2. Are you sure your TV supports Dolby Vision and/or HDR10 content? (eg. usually in other videos app)
3. Are the videos all .MKV and .MP4 files?
4. In Settings > All Videos, there is an option for a Folder Filter, it has a test option... can you tun that and tell me what numbers it show?

Currently, it's not clear how the app decides which videos are visible or are playable, that will be improved in future updates.

**Comment by CodenameFalcon** [comment]
Hi there!
I apologized for the late reply. Here is a picture of the test targeting the folder with the videos. I am not using Apple videos for local playback. I'm using other videos to work in between the Apple videos. Is this supported? I thought it would be great to have a mix of others as well.
![20221029_201821](https://user-images.githubusercontent.com/85072000/198857198-2532c150-a356-46fa-9f08-5d79fcd47a00.jpg)

**Comment by theothernt** [comment]
Thanks for the image, it helps a lot.

Using a mix of videos is supported - remote Apple videos, some local videos on a USB drive, more videos on a network share, etc.

From the image above, it looks like only 41 of the 58 videos have supported file extensions such a MP4 or MKV. Do some of the videos use other file extensions? maybe .AVI ?

**Comment by CodenameFalcon** [comment]
Yes I have videos using MKV, MP4 & TS.
Will you update it to allow other formats such as TS?

**Comment by theothernt** [comment]
The video player I use, ExoPlayer (made by Google), does seem to support .TS files.

I'm not able to test that file format at the moment, so I'll let you know when the next update is out so you can test it.

**Comment by CodenameFalcon** [comment]
I noticed you masde reference to local playback as being for the Apple videos. Does the screensaver officially support non-Apple videos to add into the mix, or is it looking for something specific in the videos to determine that they are Apple videos?
For example I am using some videos from 4ksamples.tumblr.com

**Comment by theothernt** [comment]
Yes, it does support playback of any other videos you have - assuming the file format is supported.

When you use Apple videos, they have specific filenames which Aerial Views recognises and shows the correct location or points of interest.

**Comment by theothernt** [comment]
.TS file support has been added and is live in v1.4.0 🥳
