### ISSUE TITLE
Unable to Activate on Chromecast for Google TV

### ISSUE THREAD

**Issue by Faisalthe01** [theothernt/AerialViews#80]
Hi,

i am using Chromecast with Google TV 4K

I tried connecting with adb but when i enter the command it throws an error.

any idea what is going on?

![C42F38AC-044D-44B3-B26E-BF7FCD2A5793](https://user-images.githubusercontent.com/62862684/196418800-42a13f19-7dba-4712-adfe-0bff19691b6f.jpeg)

**Comment by Faisalthe01** [comment]
> Have you used developer mode previously? and were you able to execute ADB commands without issue?
> 
> Also, do you have the Google TV 4K and have just updated to Android 12?

Hi, yes its Android 12, updated a few days ago and i was able to do ADB commands before with Android 10 without an issue.

anyway, today morning i tried again a few more times and the command worked for some reason and screensavers started to work. Thank you.

**Comment by theothernt** [comment]
That's great to hear, if you have any more questions or issues - let me know!
