### ISSUE TITLE
Location Text is Blurry on Sony A80J (and other 4K TVs)

### ISSUE THREAD

**Issue by kennethshsu** [theothernt/AerialViews#81]
**What were you trying to do...**
When the location text is enabled, the text appears blurry. The clock text is very clear.

**And what actually happened (ie. describe the bug)...**
Text appears blurry

**What kind of device do you have? (eg. Nvidia Shield, Sony TV, etc)...**
Sony A80J (2021)

**Comment by theothernt** [comment]
Thanks for reporting the issue. 

Is there any way you could take a photo or screenshot of the text so I have a better idea?

Also, are you running the latest version of the app?

**Comment by kennethshsu** [comment]
I tried taking a picture but I don't think it captures what you actually see. I'm on v1.3.2 from the Play store.

The best way for me to describe the problem is that, for some character with straight lines, for example "H", or "L", the lines don't sit tightly within a set pixel column, they "spills over".

**Comment by theothernt** [comment]
So my guess is that in certain languages the text/characters might not look right due to the text size. I'll add this to a list of things to test in future (eg. Russian, Chinese, Japanese, etc).

The fix would be to allow you to tweak the text size a bit - if the default for English is 10pt, then I should add option for 12pt, 14pt, etc which should fix the issue.

**Comment by kennethshsu** [comment]
We can try that, but I'm seeing the problem with English as well. 

Please keep me posted when you release a new version and I can help you watch for it. Thank you!

**Comment by Nxt3** [comment]
I am seeing the same thing on my Hisense U8G. I think the problem stems from the [thin font + shadow](https://github.com/theothernt/AerialViews/blob/master/app/src/main/res/values/styles.xml)

If the fonts were changed to maybe just sans-serif, that might fix it? or maybe removing or adjusting the shadow on those words.

**Comment by theothernt** [comment]
> I am seeing the same thing on my Hisense U8G. I think the problem stems from the [thin font + shadow](https://github.com/theothernt/AerialViews/blob/master/app/src/main/res/values/styles.xml)

And just to confirm, this is a 4K screen?

**Comment by Nxt3** [comment]
> > I am seeing the same thing on my Hisense U8G. I think the problem stems from the [thin font + shadow](https://github.com/theothernt/AerialViews/blob/master/app/src/main/res/values/styles.xml)
> 
> And just to confirm, this is a 4K screen?

That is correct, 4k.

Here's a pic, but honestly, the camera isn't capturing the issue. It looks somewhat blocky/pixelated irl.

![PXL_20221107_213201010.MP.jpg](https://user-images.githubusercontent.com/2940826/200425864-6774d928-d683-41ec-8499-913a12ec6e59.jpg)

**Comment by kennethshsu** [comment]
Are you seeing no or less of an issue when the video is not HDR? I think that the issue is more severe when HDR videos are playing in the background, but it's hard to visually confirm this.

**Comment by theothernt** [comment]
Would either of you be interested in trying a beta version of the app - I can make some changes to the font size and see if that fixes the issue?

**Comment by Nxt3** [comment]
> Are you seeing no or less of an issue when the video is not HDR? I think that the issue is more severe when HDR videos are playing in the background, but it's hard to visually confirm this.

I would need to check this. I've only been using HDR content.



> Would either of you be interested in trying a beta version of the app - I can make some changes to the font size and see if that fixes the issue?

Yes! Would love to help out.

**Comment by kennethshsu** [comment]
> Would either of you be interested in trying a beta version of the app - I can make some changes to the font size and see if that fixes the issue?

Yap, I can help test this as well.

**Comment by kennethshsu** [comment]
> > Are you seeing no or less of an issue when the video is not HDR? I think that the issue is more severe when HDR videos are playing in the background, but it's hard to visually confirm this.
> 
> I would need to check this. I've only been using HDR content.
> 

You can download a SDR video and try to play it locally. Or just select the SDR Apple stream from the menu. Let me know what you see, I'm curious as well.

**Comment by theothernt** [comment]
Thanks to you both!

I should have a build ready in the next day or so. The plan is to add a couple of extra options...

1. Toggle the shadow on and off 
2. Change the size of the text from a preset list

**Comment by kennethshsu** [comment]
Great, happy to help test out these options when ready.

**Comment by theothernt** [comment]
Ok, here is a test version of the app: [Aerial Views v1.3.3 Beta 1](https://www.dropbox.com/s/8xakkxnscdeoq0v/aerial-views-1.3.3-beta1.apk?dl=0)

**Comment by kennethshsu** [comment]
I see the new options now. It's hard to see if it's improved because I had to uninstall the stable version so I can't directly compare.

Disabling drop shadow I think improved it the most, I'm now on 22 points for location text size. However, removing the drop shadow makes it harder to read with some videos, can we try uniformed outlines or something else?

Also, can you put the version somewhere in the app?

**Comment by kennethshsu** [comment]
I just got a chance to do a bit more testing. I don't think the problem is from the font size or the drop shadow effect. If you pay close attention, when you advance to the next video, the texts are perfectly clear for a split second at the beginning of the video.

**Comment by theothernt** [comment]
Thanks for the update @kennethshsu.

Typically when a video starts, the text is faded in. So this could be an issue with the way Android handles fades. I may add some options into Beta 2 to disable the fading and see what happens (as I'm unable to test any of this at the moment)

**Comment by kennethshsu** [comment]
Is there a reason why the clock is ok but the location text isn't?

Let me know if you want me to help test another release. Thanks for the hard work!

**Comment by theothernt** [comment]
Well, that's the issue I'm trying to figure out. The only technical differences are the size of the text and the transparency + shadow settings. I may make them both have the same settings just to see if that fixes the issue.

**Comment by kennethshsu** [comment]
Ok sounds good, please keep me posted.

**Comment by theothernt** [comment]
Here is an update version: [Aerial Views v1.3.3 beta 2](https://www.dropbox.com/s/m722zptwvps46wp/aerial-views-1.3.3-beta2.apk?dl=0)

Basically, the Clock and Location text have the same values in terms of colour, opacity and shadow.

Let me know if it makes a difference?

**Comment by kennethshsu** [comment]
I'm still seeing the same issue. Do they have the same font style?

**Comment by theothernt** [comment]
> I'm still seeing the same issue. Do they have the same font style?

Yes, but I'll go through the code again and see if anything is changed at run-time.

**Comment by theothernt** [comment]
Just to rule out recent changes to the app, would it be possible for you to test an older version of the app...

Maybe v1.1 or v1.2 ?

**Comment by kennethshsu** [comment]
Sure, can you upload the apks here?

**Comment by theothernt** [comment]
> Sure, can you upload the apks here?

Yes, they're [all on the Releases page](https://github.com/theothernt/AerialViews/releases).

**Comment by kennethshsu** [comment]
Hmm, so I looked at v1.2. 

v1.2 looks pretty bad. Both the time and location texts are extremely hard to read, especially on brighter videos. However, it's even worse for location text compared to the time. Comparing between version (v1.2 vs the beta), the location texts are the same, but the time text is much easier to read now.

What changed?

**Comment by theothernt** [comment]
Between those two versions, I brightened the text and made it less transparent - but I'm only able to test on 1080p / SDR at the moment.

My guess is there's an issue with displaying text (which I think is in SDR) on top of a HDR video. The video will always be brighter. I'll have to do some more research.

**Comment by kennethshsu** [comment]
You need someone to donate you a 4k HDR TV! 🤣

Can you make a slider or menu option for the text transparency/brightness? I can help test that too.

**Comment by theothernt** [comment]
Another small update to test... [Aerial Views v1.3.3 beta 3](https://www.dropbox.com/s/5vudjcfwtey4522/aerial-views-1.3.3-beta3.apk?dl=0)

The text (time and location) is set to full white - just curious if this will look any better than the off-white colour I was using previously.

**Comment by kennethshsu** [comment]
v1.3.3 beta 3 made no difference as well. 

However, I found something that might be useful to you. When I launch screensaver from within the app by testing the screensaver, the problem isn't there. However, if the screensaver is launched by the OS, the problem shows up. This behavior is observable from the stable version that is currently on the Google Play Store as well.

I wonder if this is an OS problem?

**Comment by kennethshsu** [comment]
I just tested Aerial Dream, the texts don't look as white as Aerial View's clock, which is the desired look. Aerial Dreams clock and location text don't look blurry though, they just aren't as white or as bright. 

Aerial Dream's testing screensaver button vs screensaver launches by the OS look identical to me.

**Comment by theothernt** [comment]
Ah, I forgot - I don't think Aerial Dream plays the HDR versions of the videos, are you seeing Dolby Vision being activated?

Also, with Aerial Views, are you not seeing the issue if you use the 4K SDR version of the videos?

**Comment by kennethshsu** [comment]
You are right, Aerial Dream plays all videos in SDR, which is why everything looks fine.

For Aerial View, I am seeing the same issue with SDR videos: launching from the app looks ok, launching by the OS location text is blurry.

**Comment by theothernt** [comment]
If anyone has some free time, would it be possible to get some screenshots from the device itself?

After a quick search, the method seems to be - you press the power and volume down buttons simultaneously

**Comment by kennethshsu** [comment]
Wow, I think I figured out the bug.

This bug only occurs when you put the TV in "App Only Mode". @Nxt3 are you in App Only Mode? Can you try disabling that?

I only discovered this because I ran into some trouble taking screenshots when being in App Only Mode, and after some hoops I realized that the bug went away when I went out of App Only Mode.

**Comment by Nxt3** [comment]
> Wow, I think I figured out the bug.
> 
> 
> 
> This bug only occurs when you put the TV in "App Only Mode". @Nxt3 are you in App Only Mode? Can you try disabling that?
> 
> 
> 
> I only discovered this because I ran into some trouble taking screenshots when being in App Only Mode, and after some hoops I realized that the bug went away when I went out of App Only Mode.

Maybe? I'm not actually sure what "App Only Mode" is 😅

**Comment by kennethshsu** [comment]
> Maybe? I'm not actually sure what "App Only Mode" is 😅

It's basically like disabling all the smart features (like movie recommendations, sports scores, etc), it removes a bunch of junk. 

I wonder if @Nxt3 can confirm this, if so, it is indeed a system's bug and not the app and we can close out this ticket.

**Comment by theothernt** [comment]
@Nxt3 these instructions for Google TV should work...

https://support.google.com/googletv/answer/10070784?hl=en

**Comment by kennethshsu** [comment]
Actually, does that make sense, even if it works outside of App Only Mode, is this really an OS issue?

**Comment by Nxt3** [comment]
I'm definitely not in "App Only Mode".

**Comment by kennethshsu** [comment]
Interesting. By the way, @theothernt, I tried taking screenshots, but the pictures come out super weird (lots of pink colors all over the picture), I think this is due to HDR videos playing over it.

**Comment by theothernt** [comment]
> Interesting. By the way, @theothernt, I tried taking screenshots, but the pictures come out super weird (lots of pink colors all over the picture), I think this is due to HDR videos playing over it.

Damn, that's probably because screenshots are 8bit and HDR requires 10bit...

**Comment by theothernt** [comment]
I'm going to close this issue for the moment, but keep an eye out for additional font + size options in the next couple of releases.
