### ISSUE TITLE
SMB not working

### ISSUE THREAD

**Issue by CleanWillie** [theothernt/AerialViews#82]
Hello!

I have a Touchscreen on a Stand for a Museum that I want to play some videos on. since we already have several Servers, it would be convenient to connect AerialViews to a shared folder, but no matter what I do, authentication fails. Local playback works fine. 
It's a Mac server. 

We tried a Macmini Server, and a dedicated Unix NAS, with and without passwords, only letters in all the names and credentials, all to no avail.

Is SAMBA Necessary? I don#t really understand how it differs from SMB, and read a lot about hiccups on mac systems (we can't use it for sure)

**Comment by theothernt** [comment]
Thanks for reporting the issue.

Samba is just another name for SMB. SMB was invented by Microsoft, Samba is name used in open-source projects - but it's the same protocol and technology.

You've already mentioned that you've tried with and without passwords, can I get a bit more detail on...

1. What version of SMB is enabled on the server (Mac or Linux NAS)?
2. Are you trying connect via IP address or a hostname?
3. In Settings > Performance & Debug > Select SMB dialects - can you uncheck all of the SMB 3.x versions?

**Comment by CleanWillie** [comment]
Wow, thank you so much for the quick reply!

It's running SMB 3.0.2, the macOS Server version is 12.6.1.

I'm trying to connect via IP Address. I Installed a Network scanner (on the glorified tablet stand thing) for troubleshooting and it doesn't recognize the Hostname, so that wouldn't even work i guess

i CAN deselect all the SMB 3.x Versions – should I?

**Comment by CleanWillie** [comment]
Update: 

Connected it via Ethernet and switched off all SMB 3.x versions – no success.

**Comment by theothernt** [comment]
Glad to hear you found a solution!

I'll keep looking into the issue, so far it seems to [a known problem with the library I use (SMBJ) and macOS](https://github.com/hierynomus/smbj/issues/698).
