### ISSUE TITLE
Ambient mode doesnt seem to work

### ISSUE THREAD

**Issue by lthoedt** [theothernt/AerialViews#83]
Enable Aerial Dream as default "Ambient Mode"

I followed your guide and executed the command: ` adb shell settings put secure screensaver_components com.neilturner.aerialviews/.ui.screensaver.DreamActivity` , it ran without errors. (also didnt say anything but that is probably right). It doesnt work though; when i start "Ambient Mode", their default images come up instead of Aerial Dream.

I use the Chrome Cast with Google TV

**Comment by lthoedt** [comment]
I downloaded "Aerial Dreams" instead of "Aerial Views". Now i downloaded the correct app and it works perfectly!

**Comment by theothernt** [comment]
Glad to hear it worked out in the end!

If you have any further issues or questions, feel free to create a new issue.
