### ISSUE TITLE
Fire tv max adb command not found

### ISSUE THREAD

**Issue by Marius91M** [theothernt/AerialViews#85]
I have tried to activate the commamd via the Android app adb Shell Remote.

I get the following error message back:

127|kara:/ $ adb shell settings put secure screensaver_components com.neilturn
ttings put secure screensaver_components com.neilturn                         <er.aerialviews/com.neiltu
aver_components com.neilturner.aerialviews/com.neiltu                         <rner.aerialviews.ui.scree
urner.aerialviews/com.neilturner.aerialviews.ui.scree                         <nsaver.DreamActivity

/system/bin/sh: adb: not found

I use the Fire TV Stick Max with the system version Fire OS 7.6.0.8

**Comment by theothernt** [comment]
Did you find a fix?

**Comment by Marius91M** [comment]
Apparently the command does not work with the app "Remote ADB Shell". I had connected my tablet to the FireTV via this app and executed the command and this caused the error. When I tried it all again via the Windows PC with the Android SDK, it worked. Thanks a lot!
