### ISSUE TITLE
Tryng to enable on Chromecast with google TV

### ISSUE THREAD

**Issue by kieeps** [theothernt/AerialViews#86]
Fist of, love the app :)

But when i try to run "adb shell settings put secure screensaver_components com.neilturner.aerialviews/.ui.screensaver.DreamActivity" nothing actually happens, i do however run the beta version, is that does that change anything with the command? not that familiar with android :)

**Comment by theothernt** [comment]
The command does work, but sometimes ADB doesn't work properly if you've only just enabled developer mode - going on what others have reported.

I would restart your Google TV and try again. When you use the 'adb connect [ip address]', make sure it says it's connected and doesn't give an error or some other message.

The command above will work with a beta of the app, but why are you running a beta? 🙃

**Comment by kieeps** [comment]
Ah ok I'll try again :-)

Well... There was an option to join the beta program on the playstore, and bleeding edge is a lifestyle 😁

**Comment by theothernt** [comment]
Let me know how to get on with the ADB commands...

As for the beta, I don't have a beta for Aerial Views on the Play Store - is there a way to get a screenshot if possible, I'm kinda curious what you're seeing?

**Comment by kieeps** [comment]
I went back to verify if there was a beta program... And there wasn't 😅 probably messed up and looked at the wrong app or something, sorry 😁

But yeah! After restarting the device and running the command again it worked as intended 😊 thanks a lot for a great app 😁

**Comment by theothernt** [comment]
That's great to hear - on both counts 😉

If you have any other issues or questions with the app, feel free to ask!
