### ISSUE TITLE
Wifi Name and Password

### ISSUE THREAD

**Issue by kennethshsu** [theothernt/AerialViews#87]
Can we add two strings on the opposite side of time/location to show the Wifi Name and Password? It can literally be user inputs instead of pulling the info from the device.

**Comment by theothernt** [comment]
Small update - I'm hoping to have this feature out in the next release or two.

I'll be part of the ability to enable new overlays (location, weather, text, etc) and place them in 'slots' which are located at each corner of the screen.

**Comment by kennethshsu** [comment]
That's awesome, what other ideas do you have?

How about world clock too? i.e. picking a specific time zone, and display the current time there

**Comment by theothernt** [comment]
Just curious, would it over complicate things to ask people to use a line-return character for 2 lines instead of offering a Line1 and Line2 textbox, for example...

First line of text\nSecond line of text.  (notice the \n)

**Comment by kennethshsu** [comment]
I would totally say so lol... I think two text boxes will work better here.

**Comment by theothernt** [comment]
Aerial Views 1.6 has been released with the new slot/overlays system, including the ability to display custom text - let me know what you think...

https://github.com/theothernt/AerialViews/releases/tag/1.6.0
