### ISSUE TITLE
Video names (titles, points-of-interest)

### ISSUE THREAD

**Issue by kennethshsu** [theothernt/AerialViews#89]
Where does the app pull the video's name from? I need to make some changes to some locally stored videos.

**Comment by theothernt** [comment]
All of the video filenames from Apple match up with a manifest the app has internally (tvOS 12 to 15)

Eg. SE_A016_C009_HDR_20190717_HDR_4K_HEVC.mov matches to its title "Seals" or it's description.

If you change a filename you lose that automatic feature.

The only other option is to turn on Settings > Any videos > Use filenames as location and rename the files yourself...

Eg. SE_A016_C009_HDR_20190717_HDR_4K_HEVC.mov to Seals.mov or seals_off_the_coast_of_cape_peninsula,_south_africa.mov

**Comment by kennethshsu** [comment]
Can you point me to this manifest currently sits on the repo? I believe we are missing a few video's mapping. Most of them are from older Apple tvOS screensavers. 

Let me know if you need help cross-referencing.

**Comment by theothernt** [comment]
Sure, all the manifests are in this [folder](https://github.com/theothernt/AerialViews/tree/master/app/src/main/res/raw).

**Comment by theothernt** [comment]
Were there manifests of any helps?

Also, just curious, why are you using some of the older videos as opposed to all the newer tvOS 15/16 videos?

**Comment by kennethshsu** [comment]
I actually haven't looked at it at all. :(

I think there are some HDR 4k videos that were released. There's no reason, I just wanted a more variety of videos.

[Here](https://github.com/kennethshsu/Aerial_Extractor/blob/main/urls_file.txt) is the list of videos that I am using, do you want to take a look and cross validate? I think the ones I am missing are definantely the older ones.

**Comment by kennethshsu** [comment]
I actually haven't looked at it at all. :(

I think there are some HDR 4k videos that were released. There's no reason, I just wanted a more variety of videos.

[Here](https://github.com/kennethshsu/Aerial_Extractor/blob/main/urls_file.txt) is the list of videos that I am using, do you want to take a look and cross validate? I think the ones I am missing are definitely the older ones.

**Comment by theothernt** [comment]
Is there any reason you're not using all the videos from tvOS 15 or 16?

**Comment by kennethshsu** [comment]
I am definitely using all videos from tvOS 15 and 16. What I was trying to say is that I am using more than those videos.

Here is where I got all of my videos from, I am using all of them at the highest quality level available.

**Comment by theothernt** [comment]
Each year with tvOS, Apple usually add new videos but they all bring forward all the old ones - sometimes editing them slightly.

So if you have all the videos from tvOS 16, for example, there isn't any need for the older videos - if you wanted to save some space :)

That said, the app only supports tvOS15/16 (they're the same?!) for titles + points of interest. I will be adding support for older versions of the videos soon.
