### ISSUE TITLE
Add new videos to website

### ISSUE THREAD

**Issue by Hotboy1987** [theothernt/AerialViews#90]
can you add all new videos to the website

https://aerial-videos.netlify.app/

20 new videos from Jetson Creative (1080p, 4k SDR)
8 new videos from Robin Fourcade (1080p, 4k SDR)

**Comment by theothernt** [comment]
I'm hoping to improve that website soon, but in the meantime the raw list is here...

https://github.com/theothernt/AerialViews/blob/master/app/src/main/res/raw/comm1.json

https://github.com/theothernt/AerialViews/blob/master/app/src/main/res/raw/comm2.json

**Comment by Hotboy1987** [comment]
Thx man

**Comment by theothernt** [comment]
Sorry about the delay, I've finally updated the website... https://aerial-videos.netlify.app/

**Comment by Hotboy1987** [comment]
Awesome, thanks!
