### ISSUE TITLE
Screensaver doesn't start until the app is opened

### ISSUE THREAD

**Issue by wktra** [theothernt/AerialViews#92]
**What were you trying to do...**

The screensaver does not turn on until the app is actually opened. And then it works properly, turning on after the set 5 minute wait time. But after a restart, The screensaver will never turn on by itself.

**And what actually happened (ie. describe the bug)...**

Screensaver does not function.

I've tried every single auto launch program I can find. I've tried ADB commands. Nothing.

**What kind of device do you have? (eg. Nvidia Shield, Sony TV, etc)...**

I have a TCL with AndroidTV (11).

**Comment by theothernt** [comment]
So it sounds like an issue with Android TV itself not starting the screensaver.

To confirm this, can you download another free screensaver from the Play Store (eg. Dreamy) and see if that works?

Also, are you able to set any screensaver as the default on your TV?

**Comment by piaci** [comment]
same thing happens to me. 
tcl with google tv 12.

**Comment by theothernt** [comment]
> same thing happens to me. tcl with google tv 12.

And does this happen with another screensaver like the one mentioned above?

**Comment by piaci** [comment]
sorry for the late response. 
it seems the solution in #191 worked for me as well.
aerial starts without problems since then.

**Comment by theothernt** [comment]
That's great to hear, I'm glad we have a fix for TCL TVs!
