### ISSUE TITLE
Option to auto start playback when app is launched (so it's not just a screensaver)

### ISSUE THREAD

**Issue by wrybread** [theothernt/AerialViews#97]
There's really no reason for this app to be only a screensaver. It works beautifully as something that the user manually launches to watch eye candy videos on a TV. Especially now that Chromecasts don't easily allow the user to use 3rd party screensavers, very often the user will be opening this app manually and starting video playback, as opposed to waiting for the screensaver to start.

But having to launch the app and then press "test screensaver settings" to launch the videos is a bit klunky. Why not have an option where the videos start playing automatically when the app is launched, and user then presses the Back button to return to the configuration menu that is currently shown at app launch? (The screen where user selects Video Sources, Settings, Actions, etc). 

Just a suggestion, and thank you for the fantastic app. I have a drone, which means I have a ton of raw videos I made of beautiful places that usually sit on a harddrive unwatched. Now with AerialViews I have them running on a TV, looks so beautiful and thank you.

**Comment by theothernt** [comment]
Thanks for the suggestion, it has been on the list for quite a white but other features got in the way.

There is another free, image only screensaver [Dreamy](https://play.google.com/store/apps/details?id=com.samabox.dreamy) which works the way you suggest - I'll probably copy that.

**Comment by wrybread** [comment]
I found a good way to manually launch Aerial Views, or any screensaver. It's an app called Screensaver Shortcut. I couldn't find it in any app store but here's the APK:

https://apkcombo.com/screensaver-shortcut/com.computerkim.screensavershortcut/download/apk

Works well, just click it and Aerial Views (or whatever screensaver) launches right away.

**Comment by theothernt** [comment]
Glad to hear you found a fix, I had a look inside the app and it basically runs a single intent to start the screensaver. I hope to add something like that in future.

Also, in your research, did you happen to try an app called [Button Mapper](https://play.google.com/store/apps/details?id=flar2.homebutton) ?

**Comment by wrybread** [comment]
> did you happen to try an app called [Button Mapper](https://play.google.com/store/apps/details?id=flar2.homebutton)

I use and love Button Mapper. Someone else recommended it as a way to start the screensaver too, but I couldn't find a way to do it. Have you successfully launched the screensaver with it?

**Comment by wrybread** [comment]
And thinking about this more, if you made an APK that simply starts Aerial Views in its "test screensaver settings", that would be a nice way of solving this issue. The advantage over using Screensaver Shortcut is that it would allow the user to start Aerial Views' video playback even if they're using a screensaver other than Aerial Views, or no screensaver at all.

**Comment by theothernt** [comment]
So you can use Button Mapper although you need the Pro version...

1. Go to **Add Buttons**, then choose the button to customise
2. Then choose **Advanced** and select **Broadcast intent**
3. Use the following values...

    **Package:** com.android.systemui
    **Component:** .Somnambulator
5. Enable the **Start as activity** then click ok
