### ISSUE TITLE
Video Length Feature Not Working

### ISSUE THREAD

**Issue by BatJoe** [theothernt/AerialViews#99]
First thank you for adding this new video length feature.

I have tried testing it on my nVidia Shield Pro and it does not seem to be working. I have tried setting it to 10, 20, 30 seconds and the video still plays the original video length.

**Comment by theothernt** [comment]
You're correct. I'm not sure what happened but I appear to have made a mistake in the code.

I've just fixed and tested it, so it'll be in the next release soon.

Thanks again for reporting the issue, I had no idea is wasn't working ?!

**Comment by theothernt** [comment]
That release is now out, so please let me know if you have further issues.

**Comment by theothernt** [comment]
It appears there's another bug - if the video is shorter than the limit, the video will just stop until it reaches the limit. It'll be fixed in the next release.
